### ISSUE TITLE
Apache 2.4.17 mod_autoindex incompatibility

### ISSUE THREAD

**Issue by r-a-c** [phusion/passenger#1648] opened 2015-10-21 09:00 UTC
Hello, 

Just reporting apache 2.4.17 breaks phusion passenger . I do not know if this is a passenger problem or no. I think it is not.

https://bz.apache.org/bugzilla/show_bug.cgi?id=58498
In my servers , the apps just do not load, like if passenger would not be present. 

I forgot to add: 4.0.57

**Comment by OnixGH** [comment] 2015-10-21 09:13
Thanks for reporting. We became are aware of this on [the forum](https://groups.google.com/forum/#!topic/phusion-passenger/jiOpv9Isua4) and through this [pull request](https://github.com/phusion/passenger/pull/1642).

Can you confirm your issue started when you upgraded Apache (no other changes)?

**Comment by r-a-c** [comment] 2015-10-21 09:27
Hello

Yes, i can confirm. I patched source code with the revert patch

https://bz.apache.org/bugzilla/attachment.cgi?id=33183

And then passenger worked fine

(Still apache 2.4.17 breaks fastcgi apps,  what a mess, not a usable release -not related with passenger- this other issue)

**Comment by FooBarWidget** [comment] 2015-10-22 07:49
Closing this issue because it is a duplicate of #1642. If you have further comments, please continue in that thread.

**Closed** 2015-11-02 18:15 UTC
