### ISSUE TITLE
Resisting deployment error

### ISSUE THREAD

**Issue by dmitry** [phusion/passenger#1445] opened 2015-03-20 11:40 UTC
Once a week or twice, we are getting the:

```
  Resisting deployment error!
  Requests in queue: 356
```

With only 2 alive instances, instead of 24.

I don't see much errors are happening before this issue.

Can you give me an idea how I can trace it and show you the log information so you are able to fix it?

**Comment by d-snp** [comment] 2015-03-20 13:44
Hi Dmitry,

Resisting deployment errors pop up when you initiate a rolling restart and new application instances throw an error. There should be an error in the log immediately before the "Resisting deployment error!" message. Either in the nginx error log or in your application log. At least there should be a log of a non-2xx/3xx http request. If there's not something weird is going on.

**Comment by dmitry** [comment] 2015-03-20 23:39
@d-snp the thing is we are not deploying anything while that happens. Application just runs for a day without any changes (no restarts or anything like that). I will try to investigate and provide more information once it will happen again. I believe it happens when we are receiving some number of errors, and application want to revert back or something like that. For now touching the `tmp/restart.txt` is the fastest way to fix this issue.

**Comment by OnixGH** [comment] 2015-03-25 13:52
@dmitry: when you have only 2/24 instances and you get that error it means the server was not loaded but received some extra traffic and wanted to spawn a new instance, which failed.

In the other thread you mentioned that you are also experiencing a "Too many open files" error:
https://github.com/phusion/passenger/issues/1439

It's possible that the file limit was reached exactly when Passenger was trying to spawn, thus resulting in the "Resisting deployment error" notice. So it would be best to focus on the "Too many open files" error first. Of course if you can confirm that these two are related that would also help.

**Comment by dmitry** [comment] 2015-03-27 13:21
Looks like the problem was that we had only 4000 in /proc/sys/fs/file-max. We now increased it to the 64000, and no more "Resisting deployment error!" at least for now. Lets wait for some more time.

**Comment by FooBarWidget** [comment] 2015-03-27 17:58
In that case, the "resisting deployment error" issue you're experiencing is probably a red herring. As OnixGH said, the underlying problem is probably a file descriptor leak. We'll working on that.

**Comment by OnixGH** [comment] 2015-03-31 11:58
Fixed with commit https://github.com/phusion/passenger/commit/fee107a3a4141dd3a27fd2949c8ac5728915978c as mentioned in https://github.com/phusion/passenger/issues/1439

**Closed by OnixGH** 2015-03-31 11:58 UTC
Labels: EnterpriseCustomer, Priority/Critical

**Comment by dmitry** [comment] 2015-03-31 12:22
Great, thank you guys!

**Comment by jonathanhoskin** [comment] 2015-06-09 14:42
I have recently enabled deployment error resistance. I have started getting the `Resisting deployment error!` unexpectedly.

Last deployment was 6 days ago, and this just happened today. Luckily, we send the full output of passenger-status to OpsGenie when there are problem, so I have a bit of a papertrail. 

Passenger starts queuing at 12:53:

    Version : 5.0.7
    Date : 2015-06-09 12:53:35 +0000
    Instance: XgabeoB2 (nginx/1.7.9 Phusion_Passenger/5.0.7)

    ----------- General information -----------
    Max pool size : 4
    Processes : 4
    Requests in top-level queue : 0

    ----------- Application groups -----------
    /opt/webapp/current/public (production)#default:
    App root: /opt/webapp/current
    Requests in queue: 8
    * PID: 26809 Sessions: 4 Processed: 2390 Uptime: 36m 44s
    CPU: 40% Memory : 891M Last used: 0s ago
    * PID: 6761 Sessions: 4 Processed: 614 Uptime: 8m 16s
    CPU: 54% Memory : 1317M Last used: 16s ago
    * PID: 6801 Sessions: 4 Processed: 598 Uptime: 8m 15s
    CPU: 48% Memory : 818M Last used: 4s ago
    * PID: 10255 Sessions: 4 Processed: 173 Uptime: 2m 25s
    CPU: 65% Memory : 1458M Last used: 1s ago

Then, by 13:11, it has restarted and gone error resistant:

    Version : 5.0.7
    Date : 2015-06-09 13:11:41 +0000
    Instance: XgabeoB2 (nginx/1.7.9 Phusion_Passenger/5.0.7)

    ----------- General information -----------
    Max pool size : 4
    Processes : 2
    Requests in top-level queue : 0

    ----------- Application groups -----------
    /opt/webapp/current/public (production)#default:
    App root: /opt/webapp/current
    Resisting deployment error!
    Requests in queue: 14
    * PID: 15527 Sessions: 4 Processed: 448 Uptime: 3m 51s
    CPU: 80% Memory : 1461M Last used: 1s ago
    * PID: 15578 Sessions: 4 Processed: 479 Uptime: 3m 50s
    CPU: 79% Memory : 1505M Last used: 1s ago


We are using Passenger Enterprise 5.0.7, which version is this fixed in?

**Comment by OnixGH** [comment] 2015-06-09 15:33
@jonathanhoskin we keep track of the fix version as part of the issue, in this case the root cause was tackled in 5.0.6.

You should check the logs right before the error to get an idea of what the problem is (e.g. an app upgrade?).

**Comment by jonathanhoskin** [comment] 2015-06-09 21:54
There is nothing in the Rails or Nginx logs which indicates anything went wrong around that time. As previously mentioned we haven't deployed in 6 days.

**Comment by OnixGH** [comment] 2015-06-09 23:28
@jonathanhoskin the Passenger log is the one to look for (which, depending on your setup, may not be the same as the Nginx log).

Is it possible that your server ran out of memory so that passenger couldn't spawn a new app process? The status shows about 4.5 GB use pre-resistance-mode. That could be caused memory use by the app or passenger (or both).

For analyzing passenger's use we would need the output of the `passenger-status --show=requests` and `passenger-memory-stats" commands (either in the resistance mode or whenever memory use seems high).

**Comment by jonathanhoskin** [comment] 2015-06-15 22:45
We couldn't find anything in a log anywhere which indicated what happened. We have turned this feature off as it is more trouble than it is worth.

**Comment by FooBarWidget** [comment] 2015-06-16 07:02
I think we should display the reason for entering deployment error resistance mode right in the passenger-status output. That makes it much clearer what happened.

**Comment by jonathanhoskin** [comment] 2015-06-16 07:41
+1 That would give us the confidence to keep using the feature

**Comment by FooBarWidget** [comment] 2015-06-16 07:45
I have created a separate issue for that: https://github.com/phusion/passenger/issues/1539
