### ISSUE TITLE
Too high (and non-configurable) number of core request-handling threads

### ISSUE THREAD

**Issue by pakal** [phusion/passenger#1825] opened 2016-06-13 09:40 UTC
## Issue report

**Question 1: What is the problem?**

On a shared server with 40 cores, the passenger-core process uses a very hight number of threads, most of which are for request-handling, whereas the ruby application behind is single-threaded anyway. This breaks the ulimit of my shared hosting service.

- What is the expected behavior?
Being able to configure that number of core threads (see the "--threads" option of passenger-core) from nginx, apache or standalone, instead of just defaulting this "core_thread" internal option to hardware_concurrency() value which might be very high.

I've found a dirty workaround with this patch, but only for standalone mode :  
          # PATCH \src\ruby_supportlib\phusion_passenger\standalone\start_command\builtin_engine.rb:131
          command << " --threads 2"

**Question 2: Passenger version and integration mode**: 

passenger-5.0.27 open source gem

**Question 3: OS or Linux distro, platform (including version)**:

Centos 7 x64

**Question 4: Passenger installation method**:

[ X] RubyGems + Gemfile

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:

Ruby 2.2.1

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
- For example: Heroku, Amazon Container Services, Docker 1.9 with an image based on passenger-docker

Your answer: No

**Question 7: Anything else about your setup that we should know?**

Your answer: It's an automated Webfaction setup

**Comment by OnixGH** [comment] 2016-06-13 10:30
Duplicate of: https://groups.google.com/forum/#!topic/phusion-passenger/TMfTHrcEBC4

**Closed by OnixGH** 2016-06-13 10:30 UTC
