### ISSUE TITLE
Apache-level auth, and Passenger 5

### ISSUE THREAD

**Issue by jrochkind** [phusion/passenger#1456] opened 2015-03-25 19:14 UTC
I have an app deployed with Passenger apache.

I use an enterprise SSO solution that integrates as an apache module, you protect certain URLs with a feature that is much like the built-in apache [require](http://httpd.apache.org/docs/2.2/mod/core.html#require) directive. The SSO module is actually Shibboleth. 

With Passenger 4, this all works out. I protect just certain URLs _within_ my `RackBaseURL`. When accessing those URLs, apache intercepts to require auth before even sending to Passenger; once the auth is completed, it goes to Passenger-deployed app with the proper ENV variables set by apache confirming details of the auth. 

With Passenger 5.0.5, it does not seem to be working.  The apache intercept for auth never happens, it seems to go to Passenger without the apache auth module (actually the Shibboleth plugin in this case) having the chance to intercept and ensure auth before allowing access to the URL. 

This is a problem for upgrading to Passenger. Can you give any advice or ideas?

~~~httpd
      RackBaseURI /catalyst_demo
      <Directory /opt/catalyst_feature_demos/catalyst_demo>
          RailsEnv demo
          Options -MultiViews
      </Directory>

      # Shibboleth for login, assumes shibboleth is installed and
      # configured on this server.
      <Location /catalyst_demo/shibboleth_login>
          AuthType shibboleth
          ShibRequestSetting requireSession 1
          Require valid-user
      </Location>
~~~

**Comment by FooBarWidget** [comment] 2015-03-25 19:53
There have been some reports about problems with Shibboleth, which appear to be caused by problems with environment variables. See #1446 and https://groups.google.com/forum/#!msg/phusion-passenger/bbju5Fq84xc/TZrdDEm3xuwJ. We are currently investigating the problem.

**Comment by jrochkind** [comment] 2015-03-25 20:14
Okay, thanks. I want to clarify that our problem is that the 'auth' flow isn't being triggered at all, not just that env variables aren't being passed. One could imagine a situation where the auth protection happened -- user was prompted to log in before accessing the protected URL -- but then the ENV didn't make it to the Passenger-deployed app. But that's not what's happening for me, the auth protection isn't even happening at all.  So I'm not sure if it's only a question of passing environment variables. 

It might be useful to see if this is unique to shibboleth, or if this effects any Apache-level auth?  Like the standard built-in Apache "require", which is similar functionality?  If it would be useful to see, I can try to reproduce with that, which if it reproduces, might be easier for you to reproduce locally yourselves too. 

At any rate, I'm blocked from upgrading to passenger 5, alas, until Shibboleth protection works.

**Comment by jrochkind** [comment] 2015-03-25 20:19
Oops, I think I'm wrong, the auth flow is being triggered, it maybe really is just the env. As I try to reproduce.

**Comment by FooBarWidget** [comment] 2015-03-30 09:29
Closing this issue as a duplicate.

**Closed by FooBarWidget** 2015-03-30 09:29 UTC
