### ISSUE TITLE
FreeBSD, Apache, Rails, 100% CPU usage, sonewconn: pcb xxx: Listen queue overflow

### ISSUE THREAD

**Issue by PeterMozesMerl** [phusion/passenger#1732] opened 2016-01-25 12:07 UTC
I had been running Passenger on FreeBSD with Rails for many years without a single issue.

Recently, I had an issue popped up 3 times in 3 months. Passenger gets stuck on 100% percent CPU usage for hours without any load. When it had load, the Rails site didn’t work.

I update often. It happened with various versions of "everything".

FreeBSD 10.1 - 10.2
Apache 2.4.17 - 2.4.18
Passenger 5.0.21  - 5.0.23

http://pastebin.com/guc7xxyP
http://pastebin.com/J7ETzy31
http://pastebin.com/0Ff8xUW7
http://pastebin.com/4TDpW34R
https://forums.freebsd.org/threads/sonewconn-pcb-0xff-listen-queue-overflow-already-in-queue-awaiting-acceptance.54597/#post-307813

The faulty process is still running. I can help to debug if you have an idea what to do.

Apache is running event worker. Is it good?

**Comment by FooBarWidget** [comment] 2016-01-25 12:26
With 'Passenger gets stuck', do you mean that the Passenger Core process uses 100% CPU?

Are you able to reproduce this issue, or do you have no control over when it happens?

**Comment by PeterMozesMerl** [comment] 2016-01-25 13:59
Yes, I mean that. Rails production.log is empty since the issue started (about 2:00AM, CET). Apache access.log has no interesting data. I can show you the end of the "general" apache error log (not for the virtualhost as the latter one has nothing in it).

http://pastebin.com/TgWTdhuw

I can’t check the statistics right now but I think it was a low traffic period when it happened.

I can’t reproduce the issue. It happened only 3 times in 3 months randomly, however, this time I did not restart anything. I still have the process stuck. I thought it might help debugging.

**Comment by PeterMozesMerl** [comment] 2016-01-25 14:09
I just checked the statistics. The issue happened during a period of the day when there is the lowest traffic on the site both in general and in the current case (today between 1 and 2AM, CET).

The server has no other load in it, all the crontab tasks and other things run on the other server. Which also had the same issue once, in November, 2015. 

I think the last time it happened also during a low traffic period.

**Comment by PeterMozesMerl** [comment] 2016-01-25 14:20
The server log shows just the usual dovecot and sshguard messages, however, there is something interesting. It seems to me that it died exactly at 2:00AM. There are a couple of system cron tasks that run that time.

I will try to find the logs for the previous event, but here are the current ones:

This is how production.log ends: http://pastebin.com/hKyRrMka

This is what happened during this time: http://pastebin.com/BS9LK3ue

I wonder what "adjkerntz -a" does.

**Comment by PeterMozesMerl** [comment] 2016-01-25 15:47
Unfortunately, it’s not that simple.

The issue happened on another server on 18th, December at 23:27

I, [2015-12-18T23:27:32.858988 #24608]  INFO -- : Processing by SystemController#menu_numbers as JSON
I, [2015-12-18T23:27:32.866438 #24608]  INFO -- : Completed 200 OK in 7ms (Views: 0.2ms | ActiveRecord: 1.4ms)
I, [2015-12-19T00:12:12.545138 #28593]  INFO -- : Started GET "/users/wise" for 141.101.99.43 at 2015-12-19 00:12:12 +0100

Between the second and the third line there was no log entry. Passenger was stuck.

It also happened on 31. December, 2015, 14:38. Unfortunately, I have no OS logs for these events. I have Apache logs and Rails logs though. But I guess it wasn’t a crontab job.

**Comment by FooBarWidget** [comment] 2016-01-25 17:00
I've had a debugging session with @PeterMozesMerl on Skype. It looks like the problem is exactly like what we saw in the Union Station cluster. But that was Linux and this is FreeBSD so it rules out an OS problem. His backtrace is virtually identical to the one we saw.

I think the problem lies in FdSinkChannel::onData's inner loop:

~~~
do {
	ret = ::write(watcher.fd, buffer.start, buffer.size());
} while (ret == -1 && errno == EAGAIN);
~~~

It tries to restart the write() system call if it's interrupted. That would normally be a good pattern, but it looks like non-blocking sockets may sometimes return EAGAIN instead of EWOULDBLOCK. We should handle EAGAIN the same way as EWOULDBLOCK and get rid of that retry loop.

All the evidence so far does seem to indicate that it's the write loop that's infinitely looping.

**Comment by FooBarWidget** [comment] 2016-01-25 17:01
Oh *****, I think I found the bug. The retry loop is supposed to check for EINTR, not EAGAIN. -_-

**Comment by PeterMozesMerl** [comment] 2016-01-25 18:11
@FooBarWidget Thank you for the quick response and the effort. Please tell us in the ticket when you release the fix. I will upgrade as soon as I can.

**Comment by FooBarWidget** [comment] 2016-01-25 18:51
@OnixGH I'll leave the fix to you. Reproduction steps are as we discussed on Slack.

**Comment by FooBarWidget** [comment] 2016-01-29 12:29
Closing this is as duplicate of #1709.

The fix has now been incorporated into git. We plan on releasing 5.0.24 on Monday.

**Closed by FooBarWidget** 2016-01-29 12:29 UTC
Labels: Priority/Critical

**Comment by OnixGH** [comment] 2016-01-29 14:07
Doc: https://www.phusionpassenger.com/library/config/reference/?a=passenger_socket_backlog
