### ISSUE TITLE
passenger-status reports multiple instances with the same pid

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#470] opened 2014-05-29 08:41 UTC
_From [themastermind1](https://code.google.com/u/111066376566187161786/) on September 04, 2009 10:28:25_

i've seen this one a number of times, but passenger-status detects multiple pids, but lists the 
same pid multiple times in the list of choices:

$ ls -alh /tmp/passenger.* -d
d-ws--x--x 6 root root 4.0K 2009-09-03 23:48 /tmp/passenger.30601
d-ws--x--x 6 root root 4.0K 2009-09-04 01:02 /tmp/passenger.30640

$ passenger-status
It appears that multiple Passenger instances are running. Please select a
specific one by running:

  passenger-status <PID>

The following Passenger instances are running:
  PID: 30640
  PID: 30640

Looks like ControlProcess.list returns instances that all have the same @pid set:

$ ruby -rubygems -e" require 'phusion_passenger/admin_tools/control_process'; p 
PhusionPassenger::AdminTools::ControlProcess.list "

[#<PhusionPassenger::AdminTools::ControlProcess:0x1693ef8 @path="/tmp/passenger.30601", 
@pid=30640>, #<PhusionPassenger::AdminTools::ControlProcess:0x1693d38 
@path="/tmp/passenger.30640", @pid=30640>]

Which it reads from the control_process.pid file:

$ for i in /tmp/passenger.*/control_process.pid; do echo $i; cat $i; echo; done
/tmp/passenger.30601/control_process.pid
30640
/tmp/passenger.30640/control_process.pid
30640

Not sure why this is happening, but it causes passenger to think there's actually two instances 
running and prevents it from cleaning the first one which is actually stale.

In this case, 30601 was the nginx master process. I updated the conf and sent it a -HUP, and the 
new master process that spawned was 30640. I then ran passenger-status and got the above 
error.

_Original issue: http://code.google.com/p/phusion-passenger/issues/detail?id=370_

**Comment by OnixGH** [comment] 2016-02-05 15:21
@ceecko is this issue still relevant for you? Or can I close it?

**Comment by ceecko** [comment] 2016-02-05 15:27
Thanks for coming back to me - we have migrated to a different stack so I can't reproduce this error anymore, sorry.

**Comment by OnixGH** [comment] 2016-02-05 15:45
Okay, thanks!

For anyone else experiencing something like this with the latest Passenger, please open a new issue.

**Closed by OnixGH** 2016-02-05 15:45 UTC
Labels: NeedsFeedback, SupportCentral

**Comment by FooBarWidget** [comment] 2016-02-05 15:57
I think this issue is solved. In Passenger 5 we rewrite the instance registry directory handling, which should be a lot more robust now.
