### ISSUE TITLE
Passenger 5.2.2 erros in log

### ISSUE THREAD

**Issue by Sega100500** [phusion/passenger#2053] opened 2018-03-29 11:54 UTC
Phusion Passenger 5.2.2
Linux Debian 8
Apache/2.4.10 (Debian)
sites works on Ruby 2.5.0 and 2.3.6

after first start in log file:

```
App 15550 stderr: /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.2.2/src/ruby_supportlib/phusion_passenger/preloader_
shared_helpers.rb:79:
App 15671 stdout:
App 15550 stderr: [BUG] Segmentation fault at 0x0000000000001246
App 15550 stderr: ruby 2.3.6p384 (2017-12-14 revision 61254) [x86_64-linux]
App 15550 stderr:
App 15550 stderr: -- Control frame information -----------------------------------------------
App 15550 stderr: c:0007 p:---- s:0034 e:000033 CFUNC  :detach_process
App 15550 stderr: c:0006 p:0270 s:0030 e:000029 METHOD /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.2.2/src/ruby_su
pportlib/phusion_passenger/preloader_share
App 15550 stderr: c:0005 p:0288 s:0022 e:000021 METHOD /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.2.2/src/ruby_su
pportlib/phusion_passenger/preloader_share
App 15550 stderr: c:0004 p:0143 s:0009 e:000008 CLASS  /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.2.2/src/helper-
scripts/rack-preloader.rb:157
App 15550 stderr: c:0003 p:0011 s:0006 e:000005 CLASS  /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.2.2/src/helper-
scripts/rack-preloader.rb:30
App 15550 stderr: c:0002 p:0038 s:0004 E:000240 EVAL   /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.2.2/src/helper-
scripts/rack-preloader.rb:29 [FINISH]
App 15550 stderr: c:0001 p:0000 s:0002 E:002040 (none) [FINISH]
App 15550 stderr:
App 15550 stderr: -- Ruby level backtrace information ----------------------------------------
App 15550 stderr: /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.2.2/src/helper-scripts/rack-preloader.rb:29:in `<mai
n>'
App 15550 stderr: /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.2.2/src/helper-scripts/rack-preloader.rb:30:in `<mod
ule:PhusionPassenger>'
App 15550 stderr: /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.2.2/src/helper-scripts/rack-preloader.rb:157:in `<mo
dule:App>'
App 15550 stderr: /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.2.2/src/ruby_supportlib/phusion_passenger/preloader_
shared_helpers.rb:140:in `run_main_loop'
App 15550 stderr: /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.2.2/src/ruby_supportlib/phusion_passenger/preloader_
shared_helpers.rb:79:in `accept_and_process_next_client'
App 15550 stderr: /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.2.2/src/ruby_supportlib/phusion_passenger/preloader_
shared_helpers.rb:79:in `detach_process'
App 15550 stderr:
App 15550 stderr: -- Machine register context ------------------------------------------------
App 15550 stderr:  RIP: 0x0000000000001246 RBP: 0x0000000000007a6f RSP: 0x00007ffecc0080a8
App 15550 stderr:  RAX: 0x0000000000000000 RBX: 0x000055fcf53ec6d0 RCX: 0x00007fdc8379d108
App 15550 stderr:  RDX: 0x00007fdc814bc460 RDI: 0x000000000000001e RSI: 0x0000000000007a6f
App 15550 stderr:   R8: 0x0000000000000003  R9: 0x000055fcf59a88d0 R10: 0x000055fcf5bdda20
App 15550 stderr:  R11: 0x0000000000000206 R12: 0x0000000000018000 R13: 0x000055fcf59a88d0
App 15550 stderr:  R14: 0x000055fcf59a9258 R15: 0x0000000000000001 EFL: 0x0000000000010202
App 15550 stderr:
App 15550 stderr: -- C level backtrace information -------------------------------------------
App 15550 stderr: /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.2.2/src/ruby_supportlib/phusion_passenger/utils/nati
ve_support_utils.rb:38: [BUG] Segmentation fault at 0x0000000000001306
App 15550 stderr: ruby 2.3.6p384 (2017-12-14 revision 61254) [x86_64-linux]
App 15550 stderr:
App 15550 stderr: -- Control frame information -----------------------------------------------
App 15550 stderr: c:0008 p:---- s:0044 e:000043 CFUNC
[ E 2018-03-29 16:41:27.2274 15501/Ti age/Cor/App/Implementation.cpp:305 ]: Could not spawn process for application /home/ruby/projects/zile
.work: An error occurred while starting the application. Unable to connect to the preloader's socket: Cannot connect to Unix socket '/tmp/pa
ssenger.TdgzZa4/apps.s/preloader.13gw09g': Connection refused (errno=111)
  Error ID: 2d66183d
  Error details saved to: /tmp/passenger-error-HWtcgA.html
  Message from application: An error occurred while starting the application. Unable to connect to the preloader&apos;s socket: Cannot conne
ct to Unix socket &apos;/tmp/passenger.TdgzZa4/apps.s/preloader.13gw09g&apos;: Connection refused (errno=111)<br>
<h2>Raw process output:</h2>
(empty)

App 15550 stderr:  :split_by_null_into_hash
App 15550 stderr: c:0007 p:0018 s:0040 e:000039 METHOD /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.2.2/src/ruby_su
pportlib/phusion_passenger/utils/native_su
App 15550 stderr: c:0006 p:0053 s:0036 e:000035 METHOD /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.2.2/src/ruby_su
pportlib/phusion_passenger/request_handler
App 15550 stderr: c:0005
App 15550 stderr: p:0131 s:0027 e:000026 METHOD /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.2.2/src/ruby_supportli
b/phusion_passenger/request_handler
App 15550 stderr: c:0004 p:0098 s:0017 e:000016 METHOD /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.2.2/src/ruby_su
pportlib/phusion_passenger/request_handler
App 15550 stderr: c:0003 p:0065 s:0009 e:000008 BLOCK  /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.2.2/src/ruby_su
pportlib/phusion_passenger/request_handler
App 15550 stderr: c:0002 p:0030 s:0005 e:000004 BLOCK  /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.2.2/src/ruby_su
pportlib/phusion_passenger/utils.rb:113 [FINISH]
App 15550 stderr: c:0001 p:---- s:0002 e:000001 (none) [FINISH]
App 15550 stderr:
App 15550 stderr: -- Ruby level backtrace information ----------------------------------------
App 15550 stderr: /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.2.2/src/ruby_supportlib/phusion_passenger/utils.rb:1
13:in `block in create_thread_and_abort_on_exception'
App 15550 stderr: /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.2.2/src/ruby_supportlib/phusion_passenger/request_ha
ndler.rb:416:in `block (3 levels) in start_threads'
App 15550 stderr: /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.2.2/src/ruby_supportlib/phusion_passenger/request_ha
ndler/thread_handler.rb:113:in `main_loop'
App 15550 stderr: /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.2.2/src/ruby_supportlib/phusion_passenger/request_ha
ndler/thread_handler.rb:146:in `accept_and_process_next_request'
App 15550 stderr: /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.2.2/src/ruby_supportlib/phusion_passenger/request_ha
ndler/thread_handler.rb:224:in `parse_session_request'
App 15550 stderr: /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.2.2/src/ruby_supportlib/phusion_passenger/utils/nati
ve_support_utils.rb:38:in `split_by_null_into_hash'
App 15550 stderr: /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.2.2/src/ruby_supportlib/phusion_passenger/utils/nati
ve_support_utils.rb:38:in `split_by_null_into_hash'
App 15550 stderr:
App 15550 stderr: -- Machine register context ------------------------------------------------
App 15550 stderr:  RIP: 0x0000000000001306 RBP: 0x00007fdc780016c3 RSP: 0x00007fdc77cf63c8
App 15550 stderr:  RAX: 0x0000000000000000 RBX: 0x00007fdc78001410 RCX: 0x00007fdc77cf8158
App 15550 stderr:  RDX: 0x00007fdc814bc590 RDI: 0x000055fcf59a9258 RSI: 0x000055fcf5612ab8
App 15550 stderr:   R8: 0x0000000000000003  R9: 0x000055fcf59a8bf0 R10: 0x000055fcf5bdda20
App 15550 stderr:  R11: 0x00007fdc77cf8198 R12: 0x00007fdc78001410 R13: 0x000055fcf5612ab8
App 15550 stderr:  R14: 0x000055fcf59a9258 R15: 0x0000000000000001 EFL: 0x0000000000010206
App 15550 stderr:
App 15550 stderr: -- C level backtrace information -------------------------------------------
[ W 2018-03-29 16:41:27.2326 15501/T7 age/Cor/Con/InternalUtils.cpp:96 ]: [Client 1-1] Sending 502 response: application did not send a comp
lete response
[ N 2018-03-29 16:41:27.2329 15501/Tb age/Cor/CoreMain.cpp:1075 ]: Checking whether to disconnect long-running connections for process 15671
, application /home/ruby/projects/zile.work (production)
[ W 2018-03-29 16:41:27.2925 15501/Ti age/Cor/Spa/SmartSpawner.h:752 ]: An error occurred while spawning a process: An error occurred while
starting the application. Unable to connect to the preloader's socket: Cannot connect to Unix socket '/tmp/passenger.TdgzZa4/apps.s/preloade
r.13gw09g': Connection refused (errno=111)
[ W 2018-03-29 16:41:27.2925 15501/Ti age/Cor/Spa/SmartSpawner.h:753 ]: The application preloader seems to have crashed, restarting it and t
rying again...
```

**But all sites works**.

**Comment by OnixGH** [comment] 2018-04-09 09:14
Duplicate of #2013 #2022 #2040, no indication of issue in Passenger.

**Closed by OnixGH** 2018-04-09 09:14 UTC
