### ISSUE TITLE
Invalid route name, already in use: 'new_admin_user_session' 

### ISSUE THREAD

**Issue by saydulk** [phusion/passenger#2183] opened 2019-02-25 20:58 UTC
Hello, I am using Ubuntu 16.04 LTS and having this problem please help. 
```
Invalid route name, already in use: 'new_admin_user_session' 
You may have defined two routes with the same name using the `:as` option, or you may be overriding a route already defined by a resource with the same naming. For the latter, you can restrict the routes created with `resources` as explained here: 
http://guides.rubyonrails.org/routing.html#restricting-the-routes-created (ArgumentError)
  /var/lib/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:549:in `add_route'
  /var/lib/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/mapper.rb:1562:in `add_route'
  /var/lib/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/mapper.rb:1537:in `decomposed_match'
  /var/lib/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/mapper.rb:1535:in `block in decomposed_match'
  /var/lib/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/mapper.rb:1420:in `block (2 levels) in member'
  /var/lib/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/mapper.rb:817:in `scope'
  /var/lib/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/mapper.rb:1420:in `block in member'
  /var/lib/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/mapper.rb:1666:in `with_scope_level'
  /var/lib/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/mapper.rb:1416:in `member'
  /var/lib/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/mapper.rb:1535:in `decomposed_match'
  /var/lib/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/mapper.rb:1518:in `block in match'
  /var/lib/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/mapper.rb:1508:in `each'
  /var/lib/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/mapper.rb:1508:in `match'
  /var/lib/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/mapper.rb:690:in `map_method'
  /var/lib/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/mapper.rb:651:in `get'
  /var/lib/gems/2.3.0/gems/devise-3.5.6/lib/devise/rails/routes.rb:374:in `block in devise_session'
  /var/lib/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/mapper.rb:1199:in `block in resource'
  /var/lib/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/mapper.rb:1677:in `block (2 levels) in resource_scope'
  /var/lib/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/mapper.rb:817:in `scope'
  /var/lib/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/mapper.rb:1677:in `block in resource_scope'
  /var/lib/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/mapper.rb:1666:in `with_scope_level'
  /var/lib/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/mapper.rb:1676:in `resource_scope'
  /var/lib/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/mapper.rb:1198:in `resource'
  /var/lib/gems/2.3.0/gems/devise-3.5.6/lib/devise/rails/routes.rb:373:in `devise_session'
  /var/lib/gems/2.3.0/gems/devise-3.5.6/lib/devise/rails/routes.rb:263:in `block (4 levels) in devise_for'
  /var/lib/gems/2.3.0/gems/devise-3.5.6/lib/devise/rails/routes.rb:263:in `each'
  /var/lib/gems/2.3.0/gems/devise-3.5.6/lib/devise/rails/routes.rb:263:in `block (3 levels) in devise_for'
  /var/lib/gems/2.3.0/gems/devise-3.5.6/lib/devise/rails/routes.rb:461:in `with_devise_exclusive_scope'
  /var/lib/gems/2.3.0/gems/devise-3.5.6/lib/devise/rails/routes.rb:262:in `block (2 levels) in devise_for'
  /var/lib/gems/2.3.0/gems/devise-3.5.6/lib/devise/rails/routes.rb:365:in `block in devise_scope'
  /var/lib/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/mapper.rb:941:in `block in constraints'
  /var/lib/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/mapper.rb:817:in `scope'
  /var/lib/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/mapper.rb:941:in `constraints'
  /var/lib/gems/2.3.0/gems/devise-3.5.6/lib/devise/rails/routes.rb:364:in `devise_scope'
  /var/lib/gems/2.3.0/gems/devise-3.5.6/lib/devise/rails/routes.rb:261:in `block in devise_for'
  /var/lib/gems/2.3.0/gems/devise-3.5.6/lib/devise/rails/routes.rb:237:in `each'
  /var/lib/gems/2.3.0/gems/devise-3.5.6/lib/devise/rails/routes.rb:237:in `devise_for'
  /home/username/nbici-backend/config/routes.rb:54:in `block in <top (required)>'
  /var/lib/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:432:in `instance_exec'
  /var/lib/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:432:in `eval_block'
  /var/lib/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:410:in `draw'
  /home/username/nbici-backend/config/routes.rb:1:in `<top (required)>'
  /var/lib/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
  /var/lib/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'
  /var/lib/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
  /var/lib/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
  /var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
  /var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/application/routes_reloader.rb:40:in `each'
  /var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/application/routes_reloader.rb:40:in `load_paths'
  /var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/application/routes_reloader.rb:16:in `reload!'
  /var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/application/routes_reloader.rb:26:in `block in updater'
  /var/lib/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/file_update_checker.rb:75:in `execute'
  /var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/application/routes_reloader.rb:27:in `updater'
  /var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
  /var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
  /var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
  /var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
  /var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
  /usr/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
  /usr/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  /usr/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
  /usr/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
  /usr/lib/ruby/2.3.0/tsort.rb:347:in `each'
  /usr/lib/ruby/2.3.0/tsort.rb:347:in `call'
  /usr/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
  /usr/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
  /usr/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
  /var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
  /var/lib/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
  /home/username/nbici-backend/config/environment.rb:5:in `<top (required)>'
  config.ru:3:in `require'
  config.ru:3:in `block in <main>'
  /var/lib/gems/2.3.0/gems/rack-1.6.11/lib/rack/builder.rb:55:in `instance_eval'
  /var/lib/gems/2.3.0/gems/rack-1.6.11/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:101:in `eval'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:101:in `preload_app'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:380:in `run_block_and_record_step_progress'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:188:in `<module:App>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'
```
![screenshot from 2019-02-26 02-57-04](https://user-images.githubusercontent.com/1058663/53368169-37fea100-3972-11e9-8abd-6545fe732dc9.png)

=======
My Gemfile:

```
source 'https://rubygems.org'

gem 'rails', '4.2.7.1'

gem 'pg', '0.20'
gem 'state_machine'
gem 'cancancan'
gem "active_model_serializers", "~> 0.8.0"
gem 'devise', "~> 3.5.6"
gem 'devise_token_auth'
gem 'rack-cors', :require => 'rack/cors'
gem 'conekta'
gem 'delayed_job_active_record'
gem 'pry-remote', :require => 'pry-remote'


# gem 'inherited_resources', github: 'activeadmin/inherited_resources'


gem 'activeadmin', github: 'activeadmin'
gem 'active_admin_datetimepicker'
#gem 'omniauth'
gem 'nokogiri', '~> 1.8.1'
gem 'sprockets', '3.6.3'
# To use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# To use Jbuilder templates for JSON
# gem 'jbuilderR

# Use unicorn as the app server
# gem 'unicorn'

group :development, :test do
  gem 'rspec-activejob'
  gem 'spring'
  # Call 'pry' anywhere in the code to stop execution and get a debugger console
  gem 'pry-rails'
  # Automatically call pry on exception
  gem 'pry-rescue'
  # Browse the stack on pry
  gem 'pry-stack_explorer'
  # To reload UI changes
  gem 'guard-livereload'
end

group :test do
  # Testing framework
  gem 'rspec-rails'
  # Functional testing
  gem 'capybara'
  # Testing factories
  gem "factory_girl_rails"
  # Testing coverage
  gem 'simplecov', :require => false
  # Clean database after each test
  gem 'database_cleaner'
  # Manipulate time in tests
  gem 'timecop'
end
```
![screenshot from 2019-02-26 02-57-04](https://user-images.githubusercontent.com/1058663/53368231-5d8baa80-3972-11e9-806d-1d0fab584ab1.png)

**Comment by CamJN** [comment] 2019-02-25 21:16
What leads you to suspect this is an issue with Passenger? It seems like you may have some misconfigured routes in your app.

**Comment by saydulk** [comment] 2019-02-25 22:54
@CamJN do u need more information for identify misconfigured routes in my app?

**Comment by CamJN** [comment] 2019-02-25 22:59
The reason i asked why you think passenger is involved is that you are using WEBrick as your app server not Passenger, so I don't see how Passenger could be the cause of your issue. If you need help with your app, might I suggest stackoverflow? This issue tracker is for the Passenger app server, which you aren't using.

**Comment by saydulk** [comment] 2019-02-25 23:15
@CamJN yes please suggest a stackoverflow. FYI this is what i have problem - http://104.248.220.61:3000/admin/

**Comment by CamJN** [comment] 2019-03-14 00:36
This isn't a Passenger issue, closing.

**Closed by CamJN** 2019-03-14 00:36 UTC
Labels: SupportCentral
