### ISSUE TITLE
Unable to deploy as sub URI as seen in doc

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#1158] opened 2014-05-29 10:36 UTC
_From [adrianlzt](https://code.google.com/u/108683496470844525670/) on February 10, 2014 16:24:51_

What steps will reproduce the problem? 1. Follow doc until point 4.3 ( http://www.modrails.com/documentation/Users&#37;20guide&#37;20Apache.html#_deploying_a_rack_based_ruby_application_including_rails_gt_3 )
2. Apache returns 403 What is the expected output? What do you see instead? "Hello world" What version of Phusion Passenger are you using? Which version of Rails? On what operating system? Rails 4.0.2
Apache/2.2.1
Phusion_Passenger/4.0.37
CentOS 6.4 Please provide any additional information below. Using this configuration file por apache:
RailsBaseURI /subapp
<Directory /websites/rack/public>
  Allow from all
  Options -MultiViews
  RailsEnv production
</Directory>

And creating this soft link:
ln -s /websites/rack/public /var/www/html/subapp

Works correctly

_Original issue: http://code.google.com/p/phusion-passenger/issues/detail?id=1059_

**Comment by thoughtafter** [comment] 2015-09-08 18:32
This is still an issue. The documented way to deploy to a sub-uri does not work.

**Comment by FooBarWidget** [comment] 2015-09-08 22:11
@thoughtafter Can you describe your issue in more detail? How exactly does your configuration look like, and what behavior do you observe? Any error messages?

**Comment by thoughtafter** [comment] 2015-09-11 20:24
This works, as does creating a symlink as described above:
```
<VirtualHost *:80>
  ServerName servername
  DocumentRoot /var/www/app/current/public
  Alias /app /var/www/app/current/public
  <IfModule mod_passenger.c>
    PassengerEnabled on
     PassengerBaseURI /app
   PassengerAppRoot /var/www/app/current
  </IfModule>
  <Directory /var/www/app/current/public>
    AllowOverride none
    Options SymLinksIfOwnerMatch
    Require all granted
  </Directory>
</VirtualHost>
```
This, which is the way it should work according to the documentation, using a location directive, does not work:
```
<VirtualHost *:80>
  ServerName servername
  DocumentRoot /var/www/app/current/public
  Alias /app /var/www/app/current/public
<Location /app>
  <IfModule mod_passenger.c>
    PassengerEnabled on
     PassengerBaseURI /app
   PassengerAppRoot /var/www/app/current
  </IfModule>
</Location>
  <Directory /var/www/app/current/public>
    AllowOverride none
    Options SymLinksIfOwnerMatch
    Require all granted
  </Directory>
</VirtualHost>
```
Error: "The requested URL /app/ was not found on this server."

**Comment by OnixGH** [comment] 2015-09-17 01:22
@thoughtafter both your configs work for me (without symlinking anything) on Ubuntu 14.04 with Apache 2.4 and Passenger 5. What system did you test on?

**Comment by tebayoso** [comment] 2015-09-17 13:18
I have this setup in my virtualhost and seems to be working fine, maybe it can help.
Apache + Passenger 5 + Ruby 2
```
<VirtualHost *:80>
   ServerName vision.staging.decisiv.net
   ServerAlias www.vision.staging.decisiv.net
   DocumentRoot /var/www/DecisivView/current/public
   <Directory /var/www/DecisivView/current/public>
      Allow from all
      Options -MultiViews
      Require all granted
      RailsEnv staging
   </Directory>

   # Sub Uri app
   Alias /qcadmin /var/www/decisiv-qc/current/public
   <Location /qcadmin>
      PassengerBaseURI /qcadmin
      PassengerAppRoot /var/www/decisiv-qc/current

   </Location>
   <Directory /var/www/decisiv-qc/current/public>
     Allow from all
     Options -MultiViews
     Require all granted
     RailsEnv staging
   </Directory>
</VirtualHost>
```

**Comment by thoughtafter** [comment] 2015-09-23 19:25
This is also Ubuntu 14.04 with Apache 2.4 and Passenger 5.
Is there a way to debug this? I've tried passenger-config:

passenger-config  list-instances
Name                       Description
------------------------------------------------------------------
aL0hkx6w                   Apache/2.4.7 (Ubuntu) Phusion_Passenger/5.0.18

So the rails application is clearly being created, but it's not accessible at the location path, nor at the root path.

**Comment by thoughtafter** [comment] 2015-09-23 19:43
Works:
```
<VirtualHost *:80>

    PassengerEnabled on
    DocumentRoot /var/www/app/current/public
    Alias /demo /var/www/app/current/public

    PassengerAppEnv demo
    PassengerBaseURI /demo
    PassengerAppRoot /var/www/app/current

  <Directory /var/www/app/current/public>
    Options -MultiViews
    Require all granted
  </Directory>
</VirtualHost>
```

By adding location block the app is created but RAILS_RELATIVE_URL_ROOT is not set in the env and thus /demo is attempted to be interpretted as a route and the error is ActionController::RoutingError.

```
<VirtualHost *:80>

    PassengerEnabled on
    DocumentRoot /var/www/app/current/public
    Alias /demo /var/www/app/current/public

<Location /demo>
    PassengerAppEnv demo
    PassengerBaseURI /demo
    PassengerAppRoot /var/www/app/current
</Location>

  <Directory /var/www/app/current/public>
    Options -MultiViews
    Require all granted
  </Directory>
</VirtualHost>
```

In this example, analogous to my post above, PassengerEnabled has been moved into the Location block. This causes apache to fail to forward to passenger and the error is an apache 404:

```
<VirtualHost *:80>

    DocumentRoot /var/www/app/current/public
    Alias /demo /var/www/app/current/public

<Location /demo>
    PassengerEnabled on
    PassengerAppEnv demo
    PassengerBaseURI /demo
    PassengerAppRoot /var/www/app/current
</Location>

  <Directory /var/www/app/current/public>
    Options -MultiViews
    Require all granted
  </Directory>
</VirtualHost>
```
So my example above failed because of this last case, that PassengerEnabled doesn't work within a Location block. However, now it is case 2 that interests me, why PassengerBaseURI seems to fail when within a location block.

**Comment by thoughtafter** [comment] 2015-09-23 19:52
Another piece of info:
Turning off PassengerHighPerformance somewhat fixes case 2 above. Rails app is setup at the sub-uri, though asset serving is broken.

**Comment by OnixGH** [comment] 2015-10-12 12:47
@thoughtafter hmm, I copy pasted case 1 and it's working for me (I only changed PassengerAppEnv from demo to development). My app is accessible at localhost/demo/.

As for case 2, it's best to paste the exact config when reporting, so that we would have seen you were using `PassengerHighPerformance`. Our [docs](https://www.phusionpassenger.com/library/config/apache/reference/#passengerhighperformance) explicitely warn that it can interfere with other Apache modules; in this case it seems to be messing up `mod_alias`. That's unfortunate, but considered to be a known caveat.

**Comment by FooBarWidget** [comment] 2015-10-12 12:55
Speaking of which, maybe I should get rid of PassengerHighPerformance altogether. It was originally written as an optimization in benchmarks, but everybody who benchmarks Passenger nowadays would either use the Nginx integration mode or the Standalone mode with builtin engine. I regularly see people using PassengerHighPerformance while not reading the caveats.

**Comment by thoughtafter** [comment] 2015-10-13 06:30
PassengerHighPerformance should probably be removed if it interferes with mod_alias. At the very least that should be added to known problematic modules along with mod_rewrite and mod_autoindex. Also, bug 1 also appears to be due to PassengerHighPerformance interfering with mod_alias in a way that prevents PassengerEnabled from working properly.

Obviously once I realized this system had additional passenger configuration set in a non-obvious included file my plan was to post that, but before doing so I started disabling the options one by one until I disabled PassengerHighPerformance and found that resolved the issues. I agree that people should look for such things not just by grepping for the passenger options but also for include statements that may be outside the apache directory, which is what bit me in this case. I apologize for not having better information sooner.

**Comment by OnixGH** [comment] 2015-10-13 07:22
@thoughtafter that explains it indeed, no worries. I should also remember to ask about checking for additional config files when it "just works" for me.

I'll close this issue, since the docs have changed and it doesn't appear reproducible in 5.x.

**Closed by OnixGH** 2015-10-13 07:22 UTC
Labels: CannotReproduce
