### ISSUE TITLE
Apt repo migration

### ISSUE THREAD

**Issue by glassresistor** [phusion/passenger#2275] opened 2020-05-04 21:54 UTC
## Issue report
The ubuntu ppa was broken this weekend.

```
E: Repository 'https://oss-binaries.phusionpassenger.com/apt/passenger bionic Release' changed its 'Origin' value from 'packagecloud.io/phusion/passenger' to '. bionic'
E: Repository 'https://oss-binaries.phusionpassenger.com/apt/passenger bionic Release' changed its 'Label' value from 'passenger' to '. bionic'
N: Repository 'https://oss-binaries.phusionpassenger.com/apt/passenger bionic Release' changed its 'Version' value from '1' to ''
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
```

After accepting that error update starts to work but we get this error this about "misspelt" sources.list

```
W: Skipping acquire of configured file 'Release/binary-amd64/Packages' as repository 'https://oss-binaries.phusionpassenger.com/apt/passenger bionic InRelease' doesn't have the component 'Release' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'Release/i18n/Translation-en' as repository 'https://oss-binaries.phusionpassenger.com/apt/passenger bionic InRelease' doesn't have the component 'Release' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'Release/cnf/Commands-amd64' as repository 'https://oss-binaries.phusionpassenger.com/apt/passenger bionic InRelease' doesn't have the component 'Release' (component misspelt in sources.list?)
```

**Comment by CamJN** [comment] 2020-05-04 22:11
What happens if you run `apt-get clean && apt-get update`?

The repo was migrated from using packagecloud to our own server, which accounts for the `Origin`, `Label`, and `Version` changes.

A new setup of the repo works, so I'm wondering if the inability to find the Release component might be due to a cache error.

**Comment by CamJN** [comment] 2020-05-05 07:09
In my tests `apt-get clean && apt-get update` seems to be working, so if anyone else has issues please comment.

**Comment by rien** [comment] 2020-05-05 12:38
> In my tests `apt-get clean && apt-get update` seems to be working, so if anyone else has issues please comment.

This didn't work for me, however `apt-get --allow-releaseinfo-change update` did.

**Comment by CamJN** [comment] 2020-05-05 14:29
@rien thanks, can you tell me if you tried to update first, then got the error, and then fixed it with the `--allow-releaseinfo-change` flag or if you happened to have run `apt-get clean` first before the apt update that didn't work? Just trying to nail down the exact order of commands.

**Comment by Shadowssong** [comment] 2020-05-05 14:33
@CamJN would the repo migration you mentioned in the first reply be related to why some of the packages are 404'ing? 

```
    STDERR: E: Failed to fetch https://oss-binaries.phusionpassenger.com/apt/passenger/pool/bionic/main/libn/passenger/libnginx-mod-http-passenger_6.0.2-1~bionic1_amd64.deb  404  Not Found [IP: 109.107.35.58 443]
    E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

If it's not related I will open up a new issue, thank you!

**Comment by CamJN** [comment] 2020-05-05 14:34
It is, apparently some distro's packages were not mirrored, I've already raised this issue internally and we're working on having them backfilled.

**Comment by CamJN** [comment] 2020-05-05 14:35
Though that's bionic... so that should be there.

**Comment by Shadowssong** [comment] 2020-05-05 14:39
@CamJN odd, our current images already have that package installed so I didn't notice it until an image with a newer version tried to downgrade and install the older and it failed.  I can reproduce on any of my servers by `sudo apt-get remove libnginx-mod-http-passenger` and then re-running chef which handles the install for all of the packages.  I am trying to build a fresh image now

**Comment by CamJN** [comment] 2020-05-05 14:44
@Shadowssong the paths for packages did change, does updating the metadata (`apt-get --allow-releaseinfo-change update`) help?

**Comment by CamJN** [comment] 2020-05-05 14:45
I checked and that package does exist albeit at the path https://oss-binaries.phusionpassenger.com/apt/passenger/pool/main/p/passenger/libnginx-mod-http-passenger_6.0.2-1~bionic1_amd64.deb

**Comment by rien** [comment] 2020-05-05 14:48
> @rien thanks, can you tell me if you tried to update first, then got the error, and then fixed it with the `--allow-releaseinfo-change` flag or if you happened to have run `apt-get clean` first before the apt update that didn't work? Just trying to nail down the exact order of commands.

I had two servers with the issue. Once I found that the `--allow-releaseinfo-change` flag fixed it, I performed the following commands on the second server:
```sh
aptitude -s update                             # simulate an update, which failed as expected
apt-get --allow-releaseinfo-change  # update the metadata (which again shows warnings)
aptitude -s update                             # succeeded without errors or warnings
```

**Comment by CamJN** [comment] 2020-05-05 14:48
@rien thanks for the follow up!

**Comment by Shadowssong** [comment] 2020-05-05 14:48
@CamJN yep `apt-get --allow-releaseinfo-change update` worked and I was able to reinstall the package manually and via chef.  Also looks like my new image build worked but looks like any existing servers that have this issue will require this manual command which kind of stinks

**Comment by CamJN** [comment] 2020-05-05 14:54
@Shadowssong  Yup, I know it sucks. But if I make the `Origin`, `Label`, and `Value` match the old repo now, then anyone who has fixed their repos since the migration or created new images or installs will run into the same issue. So unfortunately I've put myself into a situation where I'm faced with having to make some people's lives a little harder either way. I'm going to leave this issue open for people to find when they google the error and hopefully that will help.

**Comment by zavan** [comment] 2020-05-05 16:42
Trusty64 (https://oss-binaries.phusionpassenger.com/apt/passenger/dists/trusty/main/binary-amd64/Packages) is still giving me a 404. Is it not supported anymore?

**Comment by CamJN** [comment] 2020-05-05 17:19
@zavan technically no, as Trusty has passed out of it's maintenance period into ESM. We are looking into backfilling the new repo with the trusty packages that we have already made, but no new packages will be released.

**Comment by nathanPCD** [comment] 2020-05-05 17:58
@CamJN just adding a note here to please backfill the precise packages as well if possible.

**Comment by zavan** [comment] 2020-05-06 16:47
In case anyone needs to install the Apache module on Trusty with Chef and RVM, this works for me:

```ruby
packages = %w{
  libcurl4-openssl-dev
  apache2-dev
  libapr1-dev
  libaprutil1-dev
}

packages.each do |pkg|
  package pkg do
    action :install
  end
end

bash 'install passenger via ruby gems' do
  environment Hash[...]
  code <<-EOH
    source /usr/local/rvm/scripts/rvm
    rvmsudo gem install passenger -v 6.0.4 --no-rdoc --no-ri
    rvmsudo passenger-install-apache2-module --auto
    rvmsudo passenger-config validate-install --auto
  EOH
end
```

You'll also need to modify the path on the module configuration files (`/etc/apache2/mod-available/passenger.conf|passenger.load` in my case).

Adapted from https://www.phusionpassenger.com/docs/advanced_guides/install_and_upgrade/apache/install/oss/rubygems_rvm.html

**Comment by mikos** [comment] 2020-05-07 09:52
@CamJN Any update on getting the Trusty packages back online? We have a handful of legacy applications we can no longer deploy since this change.

**Comment by FooBarWidget** [comment] 2020-05-07 13:33
Trusty and Precise packages are now back online.

**Comment by essalorz** [comment] 2020-05-14 08:52
> apt-get --allow-releaseinfo-change update

didn't work for me :

 sudo apt-get --allow-releaseinfo-change update
Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease                                                              
Hit:3 http://security.ubuntu.com/ubuntu bionic-security InRelease                                                                
Ign:4 https://oss-binaries.phusionpassenger.com/apt/passenger bionic InRelease                                                   
Get:5 https://oss-binaries.phusionpassenger.com/apt/passenger bionic Release [8 200 B]       
Get:6 https://oss-binaries.phusionpassenger.com/apt/passenger bionic Release.gpg [833 B]
Get:7 https://oss-binaries.phusionpassenger.com/apt/passenger bionic/main amd64 Packages [14,4 kB]
Get:8 https://oss-binaries.phusionpassenger.com/apt/passenger bionic/main i386 Packages [14,4 kB]
Fetched 29,7 kB in 1s (21,1 kB/s)
Reading package lists... Done
N: Repository 'https://oss-binaries.phusionpassenger.com/apt/passenger bionic Release' changed its 'Origin' value from 'packagecloud.io/phusion/passenger' to '. bionic'
N: Repository 'https://oss-binaries.phusionpassenger.com/apt/passenger bionic Release' changed its 'Label' value from 'passenger' to '. bionic'
N: Repository 'https://oss-binaries.phusionpassenger.com/apt/passenger bionic Release' changed its 'Version' value from '1' to ''

**Comment by essalorz** [comment] 2020-05-14 08:55
> > apt-get --allow-releaseinfo-change update
> 
> didn't work for me :
> 
> sudo apt-get --allow-releaseinfo-change update
> Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
> Hit:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
> Hit:3 http://security.ubuntu.com/ubuntu bionic-security InRelease
> Ign:4 https://oss-binaries.phusionpassenger.com/apt/passenger bionic InRelease
> Get:5 https://oss-binaries.phusionpassenger.com/apt/passenger bionic Release [8 200 B]
> Get:6 https://oss-binaries.phusionpassenger.com/apt/passenger bionic Release.gpg [833 B]
> Get:7 https://oss-binaries.phusionpassenger.com/apt/passenger bionic/main amd64 Packages [14,4 kB]
> Get:8 https://oss-binaries.phusionpassenger.com/apt/passenger bionic/main i386 Packages [14,4 kB]
> Fetched 29,7 kB in 1s (21,1 kB/s)
> Reading package lists... Done
> N: Repository 'https://oss-binaries.phusionpassenger.com/apt/passenger bionic Release' changed its 'Origin' value from 'packagecloud.io/phusion/passenger' to '. bionic'
> N: Repository 'https://oss-binaries.phusionpassenger.com/apt/passenger bionic Release' changed its 'Label' value from 'passenger' to '. bionic'
> N: Repository 'https://oss-binaries.phusionpassenger.com/apt/passenger bionic Release' changed its 'Version' value from '1' to ''

you actually have to do a second time a : sudo apt-get update  , then it works

**Closed** 2020-07-06 16:15 UTC
