### ISSUE TITLE
Websocket causing Session/File Descriptor Leak

### ISSUE THREAD

**Issue by super-ienien** [phusion/passenger#1810] opened 2016-05-13 18:34 UTC
Hi there,

I'm investigating a weird comportment in phusion passenger. I'm using passenger 5.0.25

**The facts :** 

I have a nodeJS app running on passenger and using a lot of websockets via socket.io
twice a week passenger say this in the log file : 

`[ 2016-05-12 15:36:56.9730 13244/7f969c077700 Ser/Server.h:274 ]: [ServerThr.1] Cannot accept client: Too many open files (errno=24). Stop accepting clients for 3 seconds. Current client count: 494`

`[ 2016-05-12 15:36:56.9731 13244/7f969c077700 age/Cor/CoreMain.cpp:794 ]: Checking whether to disconnect long-running connections for process 8804, application /usr/share/nginx/html/app`

After this message, passenger spawn a new instance of my app without shutting down the old one. So my server have two instances running simultaneously... My app is not designed to run twice because it manages itself the load balancing and the creation of child_process. This brings the server in a very instable state...

**Investigation**

passenger-status says that i have 26 actives sessions... my app's backend say that i have only two actives sessions... there is obviously something wrong here. When i prints the active requests with passenger-status i can see that a lot of them started several hours ago. Each time those requests were socket.io's sessions like this `/app/socket.io/?uid=WHCKAI2CFFF8ROZYFFWIZAYSU51F1EPEA0Y5L0ESRMRMN6MPJJ90DZNY77ZVY0HHH6QMR5U6XNZNFTROPKBI5HIQPAQCUCKNPAS7D8ZQ1OJ04OU7ME7IFOH3938CQ2SJ&EIO=3&transport=websocket&sid=ddo_334ZYhMYkGX2AAA0`

After some tests i found that when we put a client device in standby mode (laptop, iphone etc) the websocket is disconnected from my node app but the websocket session is still active in passenger.

using `lsof -p` on the PID of the passenger process reveal that each websocket session create a file descriptor like this one `Passenger 26318 xxxxx   53u  unix 0xffff88003ce91500      0t0 183397101 /tmp/passenger.vzG8oym/apps.s/node.12og2b`

The users of my app mostly use mobile devices which often go in standby, i think this is why after a few days i get a too many files open error

Do you think something is wrong in my passenger config ? Or it could be a bug ?

Thanks

**Comment by super-ienien** [comment] 2016-05-13 18:47
I just upgraded to Passenger 5.0.28. Issue still there...

**Comment by OnixGH** [comment] 2016-05-15 22:28
Did you implement a heartbeat in your application that closes a websocket if the client no longer answers? How have you tested that the leak isn't caused by the application (keeping the socket open)?

**Comment by super-ienien** [comment] 2016-05-16 19:39
Hi thanks for your answer,

My app use [socket.io](http://socket.io/) to manage websockets. The heartbeat is done by socket.io

I know that the leak is not occuring in my app because I receive the close event of the socket but the session is still in passenger-status. Maybe the leak occurs in socket.io ? How could i check that ?

**Comment by super-ienien** [comment] 2016-05-17 11:33
And also : even if the FD Leak is due to some mistake in my app, passenger should close the old app instance before starting a new one.

**Comment by OnixGH** [comment] 2016-05-18 14:05
Yeah, I've used socket.io without issues before. I just tried Node v4.2.3 with the latest socket.io (1.4.5) and the chat example works correctly for me as far as I can see.

I logged in to the server with a laptop, then unplugged wireless. Nothing happens for about 1 minute 30 sec, and then I see (passenger loglevel 7) 4 bytes being sent from the app/socket.io (heartbeat I guess). Then 25 sec later the socket is closed by the app/socket.io and Passenger immediately follows up by closing the socket (and Sessions: goes to 0 as it should).

```
# connection
2016-05-18 15:51:40 ... [Client 4-1] Header data: "GET /socket.io/?EIO=3&transport=websoc....

# login
2016-05-18 15:51:45 ... [Client 4-1] Processing 28 bytes of application data: "\201\03242["login",{"numUsers":1}]"

# heartbeat?
2016-05-18 15:53:10 ... [Client 4-1] Processing 4 bytes of application data: "\210\002\003\350"

# socket EOF -> close
2016-05-18 15:53:34 ... [Client 4-1] Application sent EOF
2016-05-18 15:53:34 ... File descriptor closed: 56
2016-05-18 15:53:34 ... Session closed for process (pid=22640, group=/home/onix/apps/nodejs/socket.io-master/examples/chat/public (development))
2016-05-18 15:53:34 ... [Client 4-1] Disconnecting; there are now 0 active clients
```

I don't know exactly what you mean with "passenger should close the old app instance before starting a new one." but if you're talking about restarting then this is wrong. A new instance should always be started first before stopping the old instance, otherwise there a service interruption can occur, or a temporary reduction in server capacity.

**Comment by super-ienien** [comment] 2016-05-18 15:28
Thanks a lot to spend time trying reproduce my issue. I will try what you did on my server and see what happen. I'll let you know when it's done. Can you just try to put your laptop in standby instead of shuttigdown the wifi ?

When i say > passenger should close the old app instance before starting a new one.
I mean that passenger should do the same thing as it does when we restart it manually. start the app instance and close the old one. Here when i get the "too many files opened" error, it starts a new app without closing the old one.

Thanks again

**Comment by OnixGH** [comment] 2016-05-18 16:15
Standby is the same, the point of the test is to have the client silently stop responding.

Do you have the output of passenger-status before and after the "too many open files" to show more clearly what you are talking about? Also, don't cut out parts of the logfile because it becomes impossible for us to see exactly what is going on. For example, Passenger doesn't randomly shut down your application, only when it is configured to do so, so reaching the file handle limit shouldn't be the cause for that.

**Comment by super-ienien** [comment] 2016-05-18 16:26
Ok,

there is nothing else about passenger in the log file because my log level is too low. I will increase it and send you a more complete log when the error occurs.

here is my current log where you can see the old app (pid 8804) and the initialisation of the new one (pid 11361) wich starts by printing the process.env to the console after a while i get another passenger message and after i get some log of the old app :
 
`App 8804 stdout: get Engine from cache
App 8804 stdout: ENGINE disconnected : 5a7
App 8804 stdout: ENGINE connected : 5a7
App 8804 stdout: Arsene connected to /settings
App 8804 stdout: ------------BIND SOCKET TO SettingsRoom
App 8804 stdout: ---------->USER BIND SOCKET Arsene : 4
[ 2016-05-12 15:36:56.9730 13244/7f969c077700 Ser/Server.h:274 ]: [ServerThr.1] Cannot accept client: Too many open files (errno=24). Stop accepting clients for 3 seconds. Current client count: 494
[ 2016-05-12 15:36:56.9731 13244/7f969c077700 age/Cor/CoreMain.cpp:794 ]: Checking whether to disconnect long-running connections for process 8804, application /usr/share/nginx/html/app
App 8804 stdout: ENGINE disconnected : 5a7
App 8804 stdout: ------------UNBIND SOCKET OF SettingsRoom
App 8804 stdout: <---------- USER UNBIND SOCKET Arsene : 3
App 8804 stdout: ------------UNBIND SOCKET OF SettingsRoom
App 8804 stdout: <---------- USER UNBIND SOCKET Arsene : 2
App 8804 stdout: ------------UNBIND SOCKET OF SettingsRoom
App 8804 stdout: <---------- USER UNBIND SOCKET Arsene : 1
App 11361 stdout: 
App 11361 stdout: { SHELL: '/bin/bash',
App 11361 stdout:   PASSENGER_DEBUG_DIR: '/tmp/passenger.spawn-debug.XXXXNvIsys',
App 11361 stdout:   USER: 'tuituit',
App 11361 stdout:   PASSENGER_USE_FEEDBACK_FD: 'true',
App 11361 stdout:   PWD: '/home/tuituit/app',
App 11361 stdout:   NODE_PATH: '/usr/share/passenger/node',
App 11361 stdout:   SHLVL: '0',
App 11361 stdout:   HOME: '/home/tuituit',
App 11361 stdout:   LOGNAME: 'tuituit',
App 11361 stdout:   SERVER_SOFTWARE: 'nginx/1.8.1 Phusion_Passenger/5.0.25',
App 11361 stdout:   IN_PASSENGER: '1',
App 11361 stdout:   PYTHONUNBUFFERED: '1',
App 11361 stdout:   RAILS_ENV: 'production',
App 11361 stdout:   RACK_ENV: 'production',
App 11361 stdout:   WSGI_ENV: 'production',
App 11361 stdout:   NODE_ENV: 'production',
App 11361 stdout:   PASSENGER_APP_ENV: 'production',
App 11361 stdout:   RAILS_RELATIVE_URL_ROOT: '/app',
App 11361 stdout:   RACK_BASE_URI: '/app',
App 11361 stdout:   PASSENGER_BASE_URI: '/app' }
...
[ 2016-05-12 15:36:59.9735 13244/7f969c077700 Ser/Server.h:289 ]: [ServerThr.1] Resuming accepting new clients
...
App 8804 stdout: 8817 instagram process -> 'tuituit_thevoice -> \'OAuthRateLimitException: You have exceeded the maximum number of requests per hour. You have performed a total of 5001 requests in the last hour. Our general maximum limit is set at 5000 requests per hour.\''

`

**Comment by super-ienien** [comment] 2016-05-21 00:05
Hi,

So I increased the log level and reproduced the issue by putting my laptop in standby mode and bring it back from sleep. I still get 2 sessions actives in passenger when I do that...

I put the log (level 7) here. You can see at line 756 the log of my app saying that a socket is established with the user `vivien` the number at the end of the line is the number of opened sockets in my app. At this point there is 1 socket in my app and 1 active session in passenger-status. After doing the standby manipulation with my laptop you can see in the log that socket.io is reconnecting but the old socket is still open (line 2110) at this time my app and passenger-status both report 2 actives sockets/sessions. After a while, my app get the close event of the old socket (probably triggered by the heartbeat system of socket.io) at line 3306, you can see that my app now report 1 active socket. But when I go in passenger-status, there is still 2 actives sessions...

[log.txt](https://github.com/phusion/passenger/files/275591/log.txt)

I hope there is enough information for you in this log. I could eventually redo that with a high log level in socket.io if you wan't

Right now I can't put my production server in log level 7 because it's producing too much datas. So I don't have more infos to give you about the "Too many files opened" error.

I added this in my nginx.conf : passenger_max_pool_size 1

I hope this will prevent passenger to run my app twice when I'll get the error again.

Thanks!

**Comment by OnixGH** [comment] 2016-05-21 17:03
Hmm, I see something different in the logs. It shows that there are two sockets open, one of them by `Client 1-10` and the other by `Client 1-14`. But I don't see any heartbeat occurring.

For `Client 1-10`, the last data arrives at `23:27:07.7371`. From that moment on until the log ends (about 2.5 minutes later, at `23:29:55.0168`) there is nothing more that happens to that socket.

For `Client 1-14`, the last data is at `23:29:41.5550`, which means that even if there was a heartbeat, it wouldn't have had enough time yet (~1 minute 30 after last traffic) to detect a timeout, so the test was too soon to support any conclusions.

You haven't mentioned so far what versions of Node and Socket.io you are using. For now I can't say much other than that I don't see the heartbeat, so it's logical that the sessions stay open.

**Comment by super-ienien** [comment] 2016-05-21 23:11
Thanks, i did a more complete log. With full log from socket.io. I hope you'll find some clue...

> For now I can't say much other than that I don't see the heartbeat, so it's logical that the sessions stay open.

I agreed but why then socket.io send to my app the close event ?

I'm using socket.io 1.4.5 and node 5.11.1

[log_full.txt](https://github.com/phusion/passenger/files/276108/log_full.txt)

**Comment by OnixGH** [comment] 2016-05-22 12:45
You should ask questions about socket.io behaviour at their forum.

I also don't really know what your application does and how you are testing exactly, for example your log is different this time because I only see 1 open socket instead of 2 like the last time (for `Client 1-10`). And if you grep for `Client 1-10` you can see that there is still data being sent at `22:41:58`, the log ends at `22:42:10`, which is only 12 seconds later.

I just tested the socket.io chat example again with node 5.11.1 and socket.io 1.4.5, connect to chat from laptop and then standby. I don't get any issue:

```
# Markpoint laptop to standby
2016-05-22 14:28:50

# Last data:
2016-05-22 14:29:39.8280 ... [Client 1-2] Processing 4 bytes of application data: "\210\002\003\350"

# Socket closed about 30 sec after last data and about 1:20 after standby
[ 2016-05-22 14:30:08.2606 ... [Client 1-2] Event: onAppSourceData
[ 2016-05-22 14:30:08.2606 ... [Client 1-2] Application sent EOF
[ 2016-05-22 14:30:08.2606 ... [Client 1-2] Not keep-aliving application session connection
```

So as far as I can tell from the logs there doesn't appear to be an issue with Passenger, you should probably try the example too to see if it works and how they are handling socket events and what you do different, maybe the issue is there.

I'll close the issue for now. If studying their example doesn't help and you could send us a minimal app that demonstrates the problem, maybe in a virtual machine or something, I'd be happy to reopen and have a look.

**Closed by OnixGH** 2016-05-22 12:45 UTC
Labels: CannotReproduce, SupportCentral

**Comment by super-ienien** [comment] 2016-05-23 15:43
@OnixGH Ok, 

I am searching for a clue into the logs but it is very difficult to read because of the Collection system metrics happening every 5 sec. Is it possible to disable it ?

**Comment by super-ienien** [comment] 2016-05-23 15:57
I did a minimal app with socket.io. I am running this minimal app and my problematic app inside the same server.

Here is the result :  

before putting the client into standby : 
- minmal app : 1 socket connected - 1 session in passenger-status
- problematic app : 1 socket connected - 1 session in passenger-status

just after the stanby : 
- minmal app : 2 sockets connected - 2 sessions in passenger-status
- problematic app : 2 sockets connected - 2 sessions in passenger-status

1min30sec after the standby (socket.io close the server-side socket after the timeout) : 
- minimal app : 1 socket connected into the app - 2 sessions in passenger-status
- problematic app : 1 socket connected into the app - 2 sessions in passenger-status

2min after the standby (passenger close the session after the timeout only in the minimal app): 
- minimal app : 1 socket connected into the app - 1 session in passenger-status
- problematic app : 1 socket connected into the app - 2 sessions in passenger-status

There is clearly something wrong somewhere between the problematic app and passenger (nothing wrong between the problematic app and socket.io because socket.io close the socket)

May be i will find something inside the passenger logs but it is very difficult to read. Could you tell if there is a way to hide some part of the logs ? thanks

**Comment by OnixGH** [comment] 2016-06-17 14:56
What can prevent Passenger from closing a session is that the websocket is not closed.. 
I don't really understand your conclusion, the minimal app is working correctly, so the answer to me seems to be to look what the problematic app does different.
