### ISSUE TITLE
Error on new release Meteor 1.6 

### ISSUE THREAD

**Issue by Jayuda** [phusion/passenger#1998] opened 2017-10-31 02:37 UTC
## Issue report

Meteor 1.6 has been released, but I try in phussion passenger error. There is log info

```
[ E 2017-10-31 09:22:26.7284 4328/T4 age/Cor/Con/CheckoutSession.cpp:285 ]: [Client 1-1] Cannot checkout session because a spawning error occurred. The identifier of the error is d4c7cf87. Please see earlier logs for details about the error.
App 4379 stdout: 
App 4379 stderr: /var/www/test16/bundle/programs/server/boot.js:50
App 4379 stderr:     const { pause } = require("./debug.js");
App 4379 stderr:           ^
App 4379 stderr: 
App 4379 stderr: SyntaxError: Unexpected token {
App 4379 stderr:     at exports.runInThisContext (vm.js:53:16)
App 4379 stderr:     at Module._compile (module.js:373:25)
App 4379 stderr:     at Object.Module._extensions..js (module.js:416:10)
App 4379 stderr:     at Module.load (module.js:343:32)
App 4379 stderr:     at Function.Module._load (module.js:300:12)
App 4379 stderr:     at Module.require (module.js:353:17)
App 4379 stderr:     at Module.require (/usr/share/passenger/helper-scripts/node-loader.js:80:25)
App 4379 stderr:     at require (internal/module.js:12:17)
App 4379 stderr:     at Object.<anonymous> (/var/www/test16/bundle/main.js:4:1)
App 4379 stderr:     at Module._compile (module.js:409:26)
[ E 2017-10-31 09:22:28.2041 4328/Th age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /var/www/test16/bundle: An error occurred while starting the web application. It exited before signalling successful startup back to Phusion Passenger.
  Error ID: 381c21df
```

**Comment by OnixGH** [comment] 2017-10-31 11:11
I can't reproduce this, I installed Meteor 1.6 and followed the default tutorial, it works with Passenger, both in Meteor as well as in bundled (Node) mode.

```
meteor create /home/me/version1_6_app
meteor build --directory /home/me/version1_6_app_bundled
# follow Meteor instruction in /home/me/version1_6_app_bundled/bundle/README first
/home/me/version1_6_app_bundled/bundle/passenger start --app-type node --startup-file main.js
# it works
```

**Comment by vladgolubev** [comment] 2017-11-15 16:29
Doesn't work for me , same error as OP

**Comment by CamJN** [comment] 2017-11-15 16:35
@vladgolubev and @Jayuda which node version are you using?

**Comment by vladgolubev** [comment] 2017-11-15 16:46
@CamJN thanks for a quick response! I can provide as much info as required. 

I updated my project from 1.5 to 1.6 and it stopped working. I had to note Passenger did a great job running Meteor since version 1.2!! Every update was ok w/o problems.

```
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"

$ node -v
v8.9.1

$ meteor --version
Meteor 1.6
```

On Meteor 1.5 node was `4.9.1` - but I updated to latest LTS after I see project doesn't start b/c of the error above. But still no luck.

Also I ran `apt-get update && apt-get upgrade` to update Passenger.

@CamJN  do I need to update node used by Passenger in some other way?

**Comment by CamJN** [comment] 2017-11-15 16:56
That error indicates that an earlier version of node is being used. How did you install node and how are you indicating to passenger to use it?

`which -a node` can be helpful in this case.

**Comment by vladgolubev** [comment] 2017-11-15 17:01
@CamJN 

I am using [nvm](https://github.com/creationix/nvm) to install node 

Here is output:

```
$ which -a node
/root/.nvm/versions/node/v8.9.1/bin/node
/usr/local/bin/node
/usr/bin/node
```


The only thing in nginx config about node+passenger I found is this:

```
    passenger_app_type node;
    passenger_startup_file main.js;
```

**Comment by CamJN** [comment] 2017-11-15 17:03
So there are multiple paths, but some might just be symlinks, you can quickly check the versions like so:

`which -a node | while read node; do echo -n "$node: "; $node -v ; done`

**Comment by vladgolubev** [comment] 2017-11-15 17:20
@CamJN I see where you are going!

```
$ which -a node | while read node; do echo -n "$node: "; $node -v ; done
/root/.nvm/versions/node/v8.9.1/bin/node: v8.9.1
/usr/local/bin/node: v4.8.6
/usr/bin/node: v4.8.6
```

So then I did install node 8 globally by this command [taken from here](https://www.digitalocean.com/community/tutorials/how-to-install-node-js-with-nvm-node-version-manager-on-a-vps)

```
n=$(which node);n=${n%/bin/node}; chmod -R 755 $n/bin/*; sudo cp -r $n/{bin,lib,share} /usr/local

```

Then I restarted Passenger, and got the new error: 

```
module.js:664
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /var/www/XXXXXXXXXXXX/bundle/programs/server/node_modules/fibers/bin/linux-x64-57/fibers.node)
```

So then I rebuilt the project again. And what do you think? It worked ✨ 

Thank you very much, you are really nice!

**Comment by CamJN** [comment] 2017-11-15 17:23
No problem, I'm glad you got it working. Just for future reference you can tell Passenger to use a specific node with the [nodejs option](https://www.phusionpassenger.com/library/config/standalone/reference/#--nodejs-nodejs). That way you don't have to copy executables around, or worry about PATH priority.

**Comment by OnixGH** [comment] 2017-11-16 16:41
@Jayuda since your problem looks the same (using a too old version of Node, which is not a Passenger issue), I'll close this for now. Feel free to reopen if you're sure you've set up your system and Passenger to use the latest Node).

**Closed by OnixGH** 2017-11-16 16:41 UTC
Labels: CannotReproduce
