### ISSUE TITLE
Python + Hug: issue with post "content-type: multipart/form-data "

### ISSUE THREAD

**Issue by koolay** [phusion/passenger#1874] opened 2016-09-19 07:26 UTC
I have a problem that can not get form data.  

**\- first case**
 `hug`  + passager nginx   

**\- second case**
 `hug` + gunicorn + nginx  proxy 

`hug` is a web framework of python.

On the first case, can not get form data, but the second case is ok.
When post with  `application/x-www-form-urlencoded` , everything is ok.

**Comment by CamJN** [comment] 2016-11-11 01:45
Would it be possible to put together a minimal reproducible test app?

**Comment by OnixGH** [comment] 2017-01-09 11:55
@koolay we're unable to reproduce this, and it seems you have a working solution. Closing for now, we can reopen if you have an example.

**Closed by OnixGH** 2017-01-09 11:55 UTC
Labels: CannotReproduce, NeedsFeedback
