### ISSUE TITLE
Issue while Installing Passenger + Nginx on Ubuntu 18.04 LTS (with APT)

### ISSUE THREAD

**Issue by pakozack** [phusion/passenger#2273] opened 2020-04-25 15:13 UTC
Hi,
I'm installing Passenger + Nginx on Ubuntu 18.04 LTS (with APT). 
As described here
https://www.phusionpassenger.com/library/install/nginx/install/oss/bionic/
I have added 
https://oss-binaries.phusionpassenger.com/apt/passenger bionic main
in my repositories.
I have an issues during apt-get update.

root@oth03:~# apt-get update
Hit:1 http://ppa.launchpad.net/malteworld/ppa/ubuntu bionic InRelease
Hit:2 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:3 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:4 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:5 http://repo.zabbix.com/zabbix/3.4/ubuntu bionic InRelease
Hit:6 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
Ign:7 https://oss-binaries.phusionpassenger.com/apt/passenger bionic InRelease
Get:8 https://oss-binaries.phusionpassenger.com/apt/passenger bionic Release [22.8 kB]
Get:9 https://oss-binaries.phusionpassenger.com/apt/passenger bionic Release.gpg
Err:9 https://oss-binaries.phusionpassenger.com/apt/passenger bionic Release.gpg
  Connection timed out [IP: 109.107.35.58 443]
Reading package lists... Done
E: The repository 'https://oss-binaries.phusionpassenger.com/apt/passenger bionic Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by soulraven** [comment] 2020-04-25 16:21
the problem is general, also on Debian Bionic, same error

**Comment by FooBarWidget** [comment] 2020-04-25 18:55
Thanks for reporting the issue, this has been fixed now.

**Closed by FooBarWidget** 2020-04-25 18:55 UTC
Labels: SupportCentral
