### ISSUE TITLE
phusion passenger 5.0.4 only passing some environment variables

### ISSUE THREAD

**Issue by decasia** [phusion/passenger#1446] opened 2015-03-20 21:59 UTC
I have an Apache 2.2/Rails 4.2/Passenger 5.0.4 app set up to use Shibboleth for authentication. Shibboleth uses various environment variables to pass per-request user information to the Rails application. This worked correctly with 4.0.57, but with 5.0.4, none of the env variables (except REMOTE_USER) are getting passed to Rails.

Some example env variables that are not getting through: `uid`, `Shib-Authentication-Instant`.

It looks to me like Passenger does some special handling of REMOTE_USER, so probably that's why it appears when the others don't.

Is there any special config I might need in order to make sure that all environment variables are correctly passed into Rails? Or anything else I can provide to help with diagnosing?

**Comment by OnixGH** [comment] 2015-03-21 14:38
Seemingly related reports: https://groups.google.com/forum/#!msg/phusion-passenger/bbju5Fq84xc/TZrdDEm3xuwJ

Thanks for reporting, we'll post here on GitHub if we find/fix anything!

**Comment by FooBarWidget** [comment] 2015-03-25 19:53
#1456 might be a duplicate.

**Comment by jrochkind** [comment] 2015-03-26 20:00
Okay, this is reproducible without Shibboleth, it is indeed a simple env issue, easily reproducible. 

If, in an apache conf, I:

    SetEnv FOOBAR set_in_apache_conf

Then in Passenger 4.x, this `FOOBAR` env variable makes it to my passenger-deployed app. 

In Passenger 5.x, it does not. 

Since SetEnv is a useful thing to do, and even a think recommended in the passenger docs in several places, I think this is definitely a bug, and a kind of severe one, yes? 

Here is the simple rack app I used to simply test whether the env was getting passed, in config.ru:

~~~ruby
run lambda { |env|
  [
    200,
    {
      'Content-Type'  => 'text/html',
      'Cache-Control' => 'public, max-age=86400'
    },
    "Hello world: env['FOOBAR']: #{env["FOOBAR"]}"
  ]
}
~~~

In Passenger 4.x, that gets the value set with `SetEnv FOOBAR` in apache conf; in Passenger 5.x it does not.

**Comment by jrochkind** [comment] 2015-03-26 20:04
oh, I am using apache httpd 2.2.3

**Comment by FooBarWidget** [comment] 2015-03-30 09:32
Looks like we're talking about two different kinds of environment variables here. The Passenger documentation says that SetEnv allows you to set *system* environment variables. But the environment variables you're referring to in this issue are *Rack*/CGI environment variables, which are different.

In Passenger 5, we changed the internal protocol from SCGI to HTTP, making it more difficult to support arbitrary Rack/CGI variables. But I'll look into this and see what we can do.

**Comment by FooBarWidget** [comment] 2015-03-30 09:39
Can you tell me more about Shibboleth? Are the environment variables set by Shibboleth unchanging (i.e. their values depend only on the configuration), or can they change depending on e.g. the client and other circumstances?

**Comment by jrochkind** [comment] 2015-03-30 11:53
The Shibboleth environmental variables depend on the client.  

The Shibboleth apache plugin is a federated auth system, although it can also be used without federation. You configure particular apache `<Location>`s to be protected by Shibboleth. For a protected location, when the browser tries to access, the plugin redirects away to another system that, possibly after more redirects, eventually has the user login, if successful eventually redirects back to the original URL.   Back to our local apache, once a redirect back to the original URL happens and the shib plugin verifies auth happens, the shib plugin sets ENV variables for various attributes of the specific user that has auth'd.  These attributes are configurable and can have any arbitrary keys.  They would usually include the login ID of the auth'd user, but can also include other information (email, phone number, name, whatever), this other information is arbitrary, which information and what keys are used for it is configurable in shib config. The app on the other end needs access to these attributes, which it usually gets via ENV. 

Even though they are arbitrary, they are configured locally.  So it would, at minimum, make things possible if you have to configure Passenger with a a list of env to pass on to the app in apache config, maybe `PassEnv` or something. That would work, but would be an extra step and not be nearly as nice as in Passenger 4.x where all env were just automatically passed on. Since it would give you another thing to set up, and keep in sync with existing config. 

I don't entirely understand the distinction between system env and rack env (I thought all system env ended up merged into rack env)  -- but in Passenger 4.x, `SetEnv` ends up in rack env, and in Passenger 5.x it does not. That seems relevant, no? I can do another test where I see if things set by `SetEnv` are available in standard ruby `ENV`, but I suspect you already know whether they will/won't be?

**Comment by FooBarWidget** [comment] 2015-03-30 11:58
The system env is per-process. It is inherently incompatible with multithreading. It is also relatively slow. But that is another discussion, and not relevant to this issue.

The thing is, in Passenger 5, we cache the SetEnv values for performance reasons. This caching works if the SetEnv values do not change dynamically, and only depends on the contents of the configuration file. But you now tell me that this is not so, because Shibboleth may change the values depending on the client.

So I will have to get rid of the caching, and I will have to ensure that SetEnv values are passed to the Rack env. I'm not sure the caching had ever been a useful performance optimization anyway. The speedup is tiny, and everybody who truly cares about every last bit of performance would use Nginx.

**Comment by jrochkind** [comment] 2015-03-30 12:06
Yeah, it's not so much that Shib may change the values depending on the client, as that the values are _all about_ the auth'd user (not the browser, but the federated authentication that happened). The HTTP flow behind the scenes is similar to OAuth, but in this case implemented with an apache plugin rather than the app level (because it's sadly more complicated than OAuth, for better or for worse, and it would be confusing and resource-intensive to implement at the app level or create a library for every possible language/platform, so it's been implemented as an apache plugin instead). 

Sorry!

You can of course use SetEnv with dynamic values too, you can do an apache SetEnv whose values are dependent on the particular request, apache SetEnv is evaluated per request. With `SetEnvIf`, or with a  `RewriteRule` that sets env, or a combination of both, or a few other mechanisms.  Setting ENV like this is pretty much the way to pass values from apache conf to the app.  It was convenient that in passenger 4.x, this Just Worked without thinking about it and without realizing that it possibly could have not worked.  Shib probably isn't the only case where someone might want to do set env on a per-request basis and have it be able to be picked up by the app.  Although apparently Shib users are the first to notice the absence.

**Comment by FooBarWidget** [comment] 2015-03-30 13:12
I think I've solved this in commit 8dc1da667, located in the 'GH-1446' branch. Could you check? I'd like to release 5.0.6 tomorrow, so if you can verify it quickly enough then we can include it into the 5.0.6 release.

**Closed** 2015-03-30 13:12 UTC
Labels: Bounty/Medium, Priority/High, Server/Apache

**Comment by jrochkind** [comment] 2015-03-30 13:48
Sure. What's the best way to install passenger-apache from a git branch? Clone git branch, run `rake install` from inside it to install the non-released gem, then proceed as usual with gem-installed passenger apache installation?

**Comment by jrochkind** [comment] 2015-03-30 13:48
(I will try to get to this today, but it might be later today, I have some local deadlines sorry!)

**Comment by FooBarWidget** [comment] 2015-03-30 13:48
Git clone branch, ./bin/passenger-install-apache2-module.

**Comment by decasia** [comment] 2015-03-30 14:12
I will test this today as well!

**Comment by decasia** [comment] 2015-03-30 14:32
OK, I tested this and it works perfectly (on my app suite at least). All expected Shibboleth-set env variables are getting passed through normally to my Rails application.

Thanks, @FooBarWidget !

**Comment by FooBarWidget** [comment] 2015-03-30 14:32
Great. Thanks for the confirmation.

**Comment by jrochkind** [comment] 2015-03-31 15:31
I can confirm that stable-5.0 branch at 196ade41 works properly with Shibboleth for me too!

I see 5.0.6 is already out, including these changes? I'll try that one too, presumably it will be the same.

**Comment by OnixGH** [comment] 2015-03-31 15:52
@jrochkind yes, the fix is part of 5.0.6, first of the "Miscellaneous bug fixes" :)

**Comment by jrochkind** [comment] 2015-04-07 19:48
Huh, I tested this in stable-5.0 branch last week and it worked. But today I'm having trouble with actual 5.0.6 -- the Shib env variables do NOT seem to be passed into the Rails app. 

@decasia , have you tested with actual release 5.0.6 too?

For me, the env variables are being passed properly with a non-released build off of 196ade4, but **NOT** being passed properly with actual release 5.0.6.  @FooBarWidget?

**Comment by FooBarWidget** [comment] 2015-04-08 06:12
The change has been properly merged. Everything should work. Did you stop and start Apache after upgrading Passenger? That is, did you perform `apachectl stop && apachectl start`? An `apachectl restart` is not enough.

**Comment by decasia** [comment] 2015-04-08 14:54
@jrochkind, yeah, I'm using the released version of 5.0.6 and it passes shibboleth env variables just fine on my setup.

**Comment by jrochkind** [comment] 2015-04-08 15:34
Hm, I didn't realize `restart` was any different than `stop && start`. But at any rate, I did a full stop and start, same outcome. 

Odd.  My setup works fine with 196ade4, but not with 5.0.6 release.  Good to know it's working fine for @decasia, great.   Perhaps it's got something to do with the particular way that I have things set up in my apache conf, that is effected by other change between 196ade4 and 5.0.6 .  Very odd. I will keep trying to debug. 

I don't shibboleth-protect my entire virtual host or entire Passenger-deployed app, but only a particular location inside my app with an apache `<Location>`.  Worked fine in passenger 4, even worked fine in passenger 5 at 196ade4, but somehow not working in 5.0.6.  Sigh.

**Comment by decasia** [comment] 2015-04-08 15:58
For what it's worth, @jrochkind, I also have an app that only has a particular location protected by Shibboleth, and that is working just fine with 5.0.6. So maybe look at other particularities of your setup?

**Comment by OnixGH** [comment] 2015-04-08 16:15
@jrochkind our release tag for 5.0.6 is set to https://github.com/phusion/passenger/commit/239c3afd9b662b32c49661ad28853e6e7757a516, what happens if you checkout/build from that one?
If that works my guess would be that there is something about the way you install the official .6 release (through apt?) that doesn't entirely get rid of something old.

**Comment by jrochkind** [comment] 2015-04-08 17:42
I am installing the official release through rubygems, so that's probably not it. 

But let's try with a hand-built one from 239c3af, `git checkout  239c3af ; ./bin/passenger-install-apache2-module`

Okay, this is weird, the hand-built one from 239c3af also works fine. 

Let me try re-installing the 5.0.6 release from scratch, with `gem install passenger -v 5.0.6`, `passenger-install-apache2-module` again.... 

Still not working!  What the heck. I know this makes no sense.  Any ideas for how I might troubleshoot this further or provide more info to you? 

I am using a non-standard PassengerDefaultRuby, I don't know if that matters -- I install passenger using MRI 2.2.1 (set up via chruby), but set PassengerDefaultRuby to an MRI 1.9.3 .  I mention because it's one thing I can think of that might be 'weird', but everything else about Passenger seems to be working fine, and I'm not sure how that would cause a problem only with env passing and only in the gem-installed 5.0.6 but not the manually installed from git checkout version.

**Comment by FooBarWidget** [comment] 2015-04-08 17:44
PassengerDefaultRuby doesn't matter.

Let's check whether the right Passenger version is active. Can you make a curl --head request to your web app and check what the X-Powered-By header says?

**Comment by decasia** [comment] 2015-04-08 17:54
Maybe also make sure to `gem remove` any unused versions of passenger before running `gem install`? I know on my system I had to manually remove the version of passenger that I had built from git to get the standard `gem install` sequence to actually install the updated code.

**Comment by jrochkind** [comment] 2015-04-08 18:07
Okay, just to be safe I uninstalled all versions of passenger, yet again installed 5.0.6, and yet again `passenger-install-apache2-module`

Still not working. `curl --head` confirms `X-Powered-By: Phusion Passenger 5.0.6`.  Yeah, I do know this makes no sense, I'm sorry.

**Comment by jrochkind** [comment] 2015-04-08 18:09
I went further and confirmed that the _particular_ location protected by Shibboleth is also returning `X-Powered-By: Phusion Passenger 5.0.6`, this was harder since couldn't just use curl -H, had to get past shibboleth first to get to passenger. But confirmed with browser dev tools.

**Comment by FooBarWidget** [comment] 2015-04-08 20:02
Can you post all your Apache config files for inspection?

**Comment by jrochkind** [comment] 2015-04-09 14:58
Okay, my apache config files on this staging machine are a bit messy, and have been through various Passenger versions applying, messily, suggested config from past versions docs -- I'm also realizing that one odd thing is the Passenger directives do not take place inside a <VirtualHost> block, but are just at top-level apache config. But that has always worked before, and it seems odd that it would break only this feature, and especially only when installing from gem rather than source (that's the oddest thing). So may be unrelated. 

The pertinent parts of my apache config files (if you really want ALL of them, I can upload them)...

`/etc/httpd/conf/httpd.conf` includes:

~~~
   LoadModule passenger_module /home/rochkind/.rvm/gems/ruby-2.2.1/gems/passenger-5.0.6/buildout/apache2/mod_passenger.so
   <IfModule mod_passenger.c>
     PassengerRoot /home/rochkind/.rvm/gems/ruby-2.2.1/gems/passenger-5.0.6
     #PassengerDefaultRuby /home/rochkind/.rvm/gems/ruby-2.2.1/wrappers/ruby
     PassengerDefaultRuby /home/rochkind/.rvm/gems/ruby-1.9.3-p194/wrappers/ruby
   </IfModule>
~~~

`/etc/httpd/conf.d/ssl.conf`  sets up SSL configuration, as well as creates a:

     <VirtualHost _default_:443>

That doesn't have much in it, just sets up logging and such. 

`/etc/httpd/conf.d/catalyst_demo.conf` sets up a passenger app deployed at a SubURI, and Shibboleth-protects one particular path inside that app. Okay, looking at this, I realize it's not _at all_ the way current Passenger docs recommend setting things up. It was perhaps from some long-past Passenger docs. I can't quite figure out why it works at all honestly -- or why it works for everything but the env passing, and only when deployed from gem, even weirder. 

~~~
      RackBaseURI /catalyst_demo
      <Directory /opt/catalyst_feature_demos/catalyst_demo>
          RailsEnv demo
          Options -MultiViews
      </Directory>

      # Shibboleth for login, assumes shibboleth is installed and
      # configured on this server.
      <Location /catalyst_demo/shibboleth_login>
          AuthType shibboleth
          ShibRequestSetting requireSession 1
          Require valid-user
      </Location>
~~~

When I try to change this configuration to what's recommended in current Passenger docs, I can't get the app to deploy at all, I just get a 404 from apache (not passenger).  

I am going to keep trying to investigate, try to get my app deployed with config more like Passenger reccommends, also try setting up a dummy print-the-env rack app to test with.

**Comment by jrochkind** [comment] 2015-04-09 19:06
Okay. I successfully reproduced with a simple rack echo-the-env app. 

Except I'm getting really confused, it seems to be pretty non-deterministic when it occurs and when it doesn't, I change things back to what they were before, and get a different result. 

At first I thought i had solved it by using `PassengerAppGroupName`, after re-scanning the Passenger Apache docs and seeing perhaps that was relevant. Not sure if PassengerAppGroupName is expected to be required for per-request apache env being passed reliably, if multiple apps are deployed? 

But after I thought i had solved it, I got confused again -- now I'm getting it working in my simple rack repro app both with and without PassengerAppGroupName and can no longer reproduce, even though I swear I had a reliable repro before. And I still haven't been able to get it to work with-or-without PassengerAppGroup name with my actual app. 


My apache conf includes:
~~~
<VirtualHost _default_:443>
     # standard SSL setup

     # several other Passenger SubURI's which do not use shibboleth
     # then...
  
     Alias /test /opt/test/public
    <Location /test>
      PassengerBaseURI /test
      PassengerAppRoot /opt/test
   
      # without this, problem reproduces:
      #PassengerAppGroupName test_test_test
   </Location>

   # If instead of a separate location block, I protect
   # the WHOLE /test location in the above location block, problem does NOT
   # reproduce
   <Location /test/protected>
      AuthType shibboleth
      ShibRequestSetting requireSession 1
      Require valid-user
   </Location>
  <Directory /opt/test/public>
     Allow from all
     Options -MultiViews
  </Directory>
</VirtualHost>
~~~

My simple rack testing app is config.ru:
~~~
run lambda { |env|
  [
    200,
    {
      'Content-Type'  => 'text/html'
    },
    "Hello world, your env is: #{env.inspect}"
  ]
}
~~~

I still can not explain why there was a difference between installing from git checkout source and installing from gem.

**Comment by jrochkind** [comment] 2015-04-09 19:16
Okay, I think I _do_ have my real app working again with PassengerGroupName. 

1. Is it expected that PassengerGroupName might be required for this?
2. Is it possible that after adding PassengerGroupName, and then removing it, restarting apache with stop; start -- somehow Passenger will 'remember' the group name?  I am having the odd experience where it seems like once I add PassengerGroupName to the config, it makes it work, and then I can remove it again, and it somehow _keeps_ working across restarts. what?  I feel like I must be getting confused. 
3. If I have a separate <Location> block for the sub-path that is shib-protected... should I repeat the PassengerAppGroupName in there too?  <Location /test> with passenger setup, and <Location /test/protected> with shib protection, should I repeat the PassengerAppGroupName in the second one just to be sure?

And mostly, does this make sense?

Man, in many years of using Passenger, this is actually the first time I've ever had a headache like this. I hope the performance improvements that require PassengerAppGroupName (env caching?) are worth the hit to "It just works, you don't have to worry about it" that results!

**Comment by jrochkind** [comment] 2015-04-09 19:25
Also, it seems to NEED to be inside a VirtualHost now, I can't get away with my sloppy top-level <Location> blocks to define the Passenger app anymore, like I could before, even if i put the PassengerAppGroup name inside the <Location> block which is at top-level conf. 

I really have no idea if all the parts of this are intentional/expected, so I'll just stop posting now and hope @FooBarWidget has some advice, thanks!

**Comment by jrochkind** [comment] 2015-04-09 19:48
Okay, sorry, ONE more.  It looks like if I put `PassengerAppGroupName` in _both_ `<location>` blocks (the one where I define the passenger app; and the sub-one where I protect a sub-path), then things are working again, even with the `location` blocks all at top-level apache config, not in a virtual host. (Which I know is sloppy, but it's just how our infrastructure was set up a long time ago, for now).

**Comment by jrochkind** [comment] 2015-04-10 21:07
FWIW, I still don't have it reliably working, _even_ sprinkling `PassengerAppGroupName` all over the place, so the PassengerAppGroupName might have been a red herring. (Still not sure if PassengerAppGroupName is _expected_ to be neccesary here? I think the default cache key that PassengerAppGroupName sets explicitly is meant to be on PassengerAppRoot, so it ought not to be neccesary?)

Anwyay, i still don't have it working reliably -- it seems to be pretty non-deterministic whether it works or not, with the same config and no apache restart, it'll work sometimes and not others. I can't quite figure it out. 

Worse, I haven't managed to create a reproduction case with a simple rack test app, the simple rack test app seems to work fine, but my real Rails app does not. Or maybe this is just an illusion since it's non-deterministic in the first place, maybe i was just getting lucky with the simple rack test app. 

I'll keep trying to make a reproduction, but I'm hoping you can get to it through #1472, and that it's indeed the same issue. Otherwise eventually I'll give up and go back to Passenger 4.
