### ISSUE TITLE
Error: cannot load such file -- rack (LoadError)

### ISSUE THREAD

**Issue by gonace** [phusion/passenger#1911] opened 2017-01-05 16:46 UTC
**Question 1: What is the problem?**
- What is the expected behavior?
Application not starting, "cannot load such file -- rack (LoadError)"

- What is the actual behavior?
Don't know, most likely an environment problem.

**Question 2: Passenger version and integration mode**:
- For example: open source 5.0.26 standalone; enterprise 5.0.21/nginx

Your answer:
- Open source 5.1.1/nginx

**Question 3: OS or Linux distro, platform (including version)**:
- For example: Debian 8, x86_64 or OS X 10.10 Yosemite, x86_64

Your answer:
- Debian 8, x86_64

**Question 4: Passenger installation method**:
Your answer:
[ ] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[X] Phusion APT repo
[ ] Phusion YUM repo
[ ] OS X Homebrew
[ ] source tarball
[ ] Other, please specify:

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
- For example: Ruby 2.3.0, RVM, Rails 5.0.0; Node.js 4.0.0 with Express 4.13.4

Your answer:
- Ruby 1.9.3

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
- For example: Heroku, Amazon Container Services, Docker 1.9 with an image based on passenger-docker

Your answer:
- No

Error details:
```
cannot load such file -- rack (LoadError)
  /home/payway/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
  /home/payway/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:430:in `activate_gem'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:102:in `preload_app'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:156:in `<module:App>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'
```

```
Application root
/home/payway/current/apps/homer2
Environment (value of RAILS_ENV, RACK_ENV, WSGI_ENV, NODE_ENV and PASSENGER_APP_ENV)
azure_test
Ruby interpreter command
/home/payway/.rvm/gems/ruby-1.9.3-p545@tulo-httpapi/wrappers/ruby
User and groups
uid=1000(payway) gid=1000(payway) groups=1000(payway)
Environment variables
rvm_bin_path = /home/payway/.rvm/bin
GEM_HOME = /home/payway/.rvm/gems/ruby-1.9.3-p545@tulo-httpapi
SHELL = /bin/bash
IRBRC = /home/payway/.rvm/rubies/ruby-1.9.3-p545/.irbrc
PYTHONUNBUFFERED = 1
PASSENGER_DEBUG_DIR = /tmp/passenger.spawn-debug.XXXXRRSSKu
MY_RUBY_HOME = /home/payway/.rvm/rubies/ruby-1.9.3-p545
USER = payway
rvm_stored_umask = 0022
_system_type = Linux
rvm_path = /home/payway/.rvm
IN_PASSENGER = 1
RACK_ENV = azure_test
PASSENGER_USE_FEEDBACK_FD = true
rvm_prefix = /home/payway
PATH = /home/payway/.rvm/gems/ruby-1.9.3-p545@tulo-httpapi/bin:/home/payway/.rvm/gems/ruby-1.9.3-p545@global/bin:/home/payway/.rvm/rubies/ruby-1.9.3-p545/bin:/home/payway/.rvm/gems/ruby-1.9.3-p545@tulo-httpapi/bin:/home/payway/.rvm/gems/ruby-1.9.3-p545@global/bin:/home/payway/.rvm/rubies/ruby-1.9.3-p545/bin:/home/payway/.rvm/bin:/home/payway/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
WSGI_ENV = azure_test
rvm_loaded_flag = 1
PWD = /home/payway/current/apps/homer2
NODE_PATH = /usr/share/passenger/node
_system_arch = x86_64
NODE_ENV = azure_test
_system_version = 8
rvm_version = 1.28.0 (latest)
HOME = /home/payway
SHLVL = 0
RAILS_ENV = azure_test
rvm_ruby_string = ruby-1.9.3-p545
TULO_ENV = azure_test
SERVER_SOFTWARE = nginx/1.10.2 Phusion_Passenger/5.1.1
LOGNAME = payway
GEM_PATH = /home/payway/.rvm/gems/ruby-1.9.3-p545@tulo-httpapi:/home/payway/.rvm/gems/ruby-1.9.3-p545@global
PASSENGER_APP_ENV = azure_test
rvm_delete_flag = 0
RUBY_VERSION = ruby-1.9.3-p545
_system_name = Debian
rvm_user_install_flag = 1
Ulimits
Unknown
System metrics
------------- General -------------
Kernel version    : 3.16.0-4-amd64
Uptime            : 30d 0h 18m 21s
Load averages     : 0.00%, 0.02%, 0.05%
Fork rate         : unknown

------------- CPU -------------
Number of CPUs    :    1
Average CPU usage :   0%  --   0% user,   0% nice,   0% system, 100% idle
  CPU 1           :   0%  --   0% user,   0% nice,   0% system, 100% idle
I/O pressure      :   0%
  CPU 1           :   0%
Interference from other VMs:   0%
  CPU 1                    :   0%

------------- Memory -------------
RAM total         :   3453 MB
RAM used          :   1435 MB (42%)
RAM free          :   2017 MB
Swap total        :      0 MB
Swap used         :      0 MB (-nan%)
Swap free         :      0 MB
Swap in           : unknown
Swap out          : unknown

General Ruby interpreter information
RUBY_VERSION = 1.9.3
RUBY_PLATFORM = x86_64-linux
RUBY_ENGINE = ruby
RubyGems version = 2.4.8
RubyGems paths = ["/home/payway/.rvm/gems/ruby-1.9.3-p545@tulo-httpapi", "/home/payway/.rvm/gems/ruby-1.9.3-p545@global"]
Ruby configuration (RbConfig::CONFIG)
DESTDIR = 
MAJOR = 1
MINOR = 9
TEENY = 1
PATCHLEVEL = 545
INSTALL = /usr/bin/install -c
EXEEXT = 
prefix = /home/payway/.rvm/rubies/ruby-1.9.3-p545
ruby_install_name = ruby
RUBY_INSTALL_NAME = ruby
RUBY_SO_NAME = ruby
exec = exec
ruby_pc = ruby-1.9.pc
PACKAGE = ruby
BUILTIN_TRANSSRCS =  newline.c
USE_RUBYGEMS = YES
MANTYPE = doc
NROFF = /usr/bin/nroff
vendorhdrdir = /home/payway/.rvm/rubies/ruby-1.9.3-p545/include/ruby-1.9.1/vendor_ruby
sitehdrdir = /home/payway/.rvm/rubies/ruby-1.9.3-p545/include/ruby-1.9.1/site_ruby
rubyhdrdir = /home/payway/.rvm/rubies/ruby-1.9.3-p545/include/ruby-1.9.1
UNIVERSAL_INTS = 
UNIVERSAL_ARCHNAMES = 
configure_args =  '--prefix=/home/payway/.rvm/rubies/ruby-1.9.3-p545' '--disable-install-doc' '--enable-shared'
vendordir = /home/payway/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/vendor_ruby
sitedir = /home/payway/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/site_ruby
ruby_version = 1.9.1
sitearch = x86_64-linux
arch = x86_64-linux
RI_BASE_NAME = ri
ridir = /home/payway/.rvm/rubies/ruby-1.9.3-p545/share/ri
rubylibprefix = /home/payway/.rvm/rubies/ruby-1.9.3-p545/lib/ruby
MAKEFILES = Makefile
PLATFORM_DIR = 
THREAD_MODEL = pthread
SYMBOL_PREFIX = 
EXPORT_PREFIX = 
COMMON_HEADERS = 
COMMON_MACROS = 
COMMON_LIBS = 
MAINLIBS = 
ENABLE_SHARED = yes
DLDLIBS =  -lc
SOLIBS = -lpthread -lrt -ldl -lcrypt -lm 
LIBRUBYARG_SHARED = -Wl,-R -Wl,/home/payway/.rvm/rubies/ruby-1.9.3-p545/lib -L/home/payway/.rvm/rubies/ruby-1.9.3-p545/lib -lruby
LIBRUBYARG_STATIC = -Wl,-R -Wl,/home/payway/.rvm/rubies/ruby-1.9.3-p545/lib -L/home/payway/.rvm/rubies/ruby-1.9.3-p545/lib -lruby-static
LIBRUBYARG = -Wl,-R -Wl,/home/payway/.rvm/rubies/ruby-1.9.3-p545/lib -L/home/payway/.rvm/rubies/ruby-1.9.3-p545/lib -lruby
LIBRUBY = libruby.so.1.9.1
LIBRUBY_ALIASES = libruby.so.1.9 libruby.so
LIBRUBY_SO = libruby.so.1.9.1
LIBRUBY_A = libruby-static.a
RUBYW_INSTALL_NAME = 
rubyw_install_name = 
LIBRUBY_DLDFLAGS = -Wl,-soname,libruby.so.1.9
LIBRUBY_LDSHARED = gcc -shared
EXTDLDFLAGS = 
warnflags = -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration
debugflags = -ggdb
optflags = -O3
cxxflags =  -O3 -ggdb -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration
cflags =  -O3 -ggdb -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration
cppflags = 
NULLCMD = :
INSTALLDOC = nodoc
CAPITARGET = nodoc
RDOCTARGET = nodoc
EXECUTABLE_EXTS = 
ARCHFILE = 
LIBRUBY_RELATIVE = no
EXTOUT = .ext
PREP = miniruby
TEST_RUNNABLE = yes
setup = Setup
EXTSTATIC = 
STRIP = strip -S -x
TRY_LINK = 
LIBPATHENV = LD_LIBRARY_PATH
RPATHFLAG =  -Wl,-R%1$-s
LIBPATHFLAG =  -L%1$-s
LINK_SO = 
LIBEXT = a
DLEXT2 = 
DLEXT = so
LDSHAREDXX = g++ -shared
LDSHARED = gcc -shared
CCDLFLAGS = -fPIC
STATIC = 
ARCH_FLAG = 
DLDFLAGS = 
ALLOCA = 
codesign = 
POSTLINK = :
WERRORFLAG = -Werror
CHDIR = cd -P
RMALL = rm -fr
RMDIRS = rmdir --ignore-fail-on-non-empty -p
RMDIR = rmdir --ignore-fail-on-non-empty
CP = cp
RM = rm -f
PKG_CONFIG = pkg-config
DOXYGEN = 
DOT = 
MAKEDIRS = /bin/mkdir -p
MKDIR_P = /bin/mkdir -p
INSTALL_DATA = /usr/bin/install -c -m 644
INSTALL_SCRIPT = /usr/bin/install -c
INSTALL_PROGRAM = /usr/bin/install -c
SET_MAKE = 
LN_S = ln -s
NM = nm
DLLWRAP = 
WINDRES = 
OBJCOPY = :
OBJDUMP = objdump
ASFLAGS = 
AS = as
AR = ar
RANLIB = ranlib
try_header = 
COUTFLAG = -o 
OUTFLAG = -o 
CPPOUTFILE = -o conftest.i
GNU_LD = yes
GCC = yes
EGREP = /bin/grep -E
GREP = /bin/grep
CPP = gcc -E
CXXFLAGS =  -O3 -ggdb -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration
CXX = g++
OBJEXT = o
CPPFLAGS =   
LDFLAGS = -L.  -rdynamic -Wl,-export-dynamic
CFLAGS =  -O3 -ggdb -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration  -fPIC
CC = gcc
target_os = linux
target_vendor = unknown
target_cpu = x86_64
target = x86_64-unknown-linux-gnu
host_os = linux-gnu
host_vendor = unknown
host_cpu = x86_64
host = x86_64-unknown-linux-gnu
RUBYW_BASE_NAME = rubyw
RUBY_BASE_NAME = ruby
build_os = linux-gnu
build_vendor = unknown
build_cpu = x86_64
build = x86_64-unknown-linux-gnu
RUBY_RELEASE_DATE = 2014-02-24
RUBY_PROGRAM_VERSION = 1.9.3
BASERUBY = echo executable host ruby is required.  use --with-baseruby option.; false
target_alias = 
host_alias = 
build_alias = 
LIBS = -lpthread -lrt -ldl -lcrypt -lm 
ECHO_T = 
ECHO_N = -n
ECHO_C = 
DEFS = 
mandir = /home/payway/.rvm/rubies/ruby-1.9.3-p545/share/man
localedir = /home/payway/.rvm/rubies/ruby-1.9.3-p545/share/locale
libdir = /home/payway/.rvm/rubies/ruby-1.9.3-p545/lib
psdir = /home/payway/.rvm/rubies/ruby-1.9.3-p545/share/doc/ruby
pdfdir = /home/payway/.rvm/rubies/ruby-1.9.3-p545/share/doc/ruby
dvidir = /home/payway/.rvm/rubies/ruby-1.9.3-p545/share/doc/ruby
htmldir = /home/payway/.rvm/rubies/ruby-1.9.3-p545/share/doc/ruby
infodir = /home/payway/.rvm/rubies/ruby-1.9.3-p545/share/info
docdir = /home/payway/.rvm/rubies/ruby-1.9.3-p545/share/doc/ruby
oldincludedir = /usr/include
includedir = /home/payway/.rvm/rubies/ruby-1.9.3-p545/include
localstatedir = /home/payway/.rvm/rubies/ruby-1.9.3-p545/var
sharedstatedir = /home/payway/.rvm/rubies/ruby-1.9.3-p545/com
sysconfdir = /home/payway/.rvm/rubies/ruby-1.9.3-p545/etc
datadir = /home/payway/.rvm/rubies/ruby-1.9.3-p545/share
datarootdir = /home/payway/.rvm/rubies/ruby-1.9.3-p545/share
libexecdir = /home/payway/.rvm/rubies/ruby-1.9.3-p545/libexec
sbindir = /home/payway/.rvm/rubies/ruby-1.9.3-p545/sbin
bindir = /home/payway/.rvm/rubies/ruby-1.9.3-p545/bin
exec_prefix = /home/payway/.rvm/rubies/ruby-1.9.3-p545
PACKAGE_URL = 
PACKAGE_BUGREPORT = 
PACKAGE_STRING = 
PACKAGE_VERSION = 
PACKAGE_TARNAME = 
PACKAGE_NAME = 
PATH_SEPARATOR = :
SHELL = /bin/bash
rubylibdir = /home/payway/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1
archdir = /home/payway/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/x86_64-linux
sitelibdir = /home/payway/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/site_ruby/1.9.1
sitearchdir = /home/payway/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/site_ruby/1.9.1/x86_64-linux
vendorlibdir = /home/payway/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/vendor_ruby/1.9.1
vendorarchdir = /home/payway/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/vendor_ruby/1.9.1/x86_64-linux
topdir = /home/payway/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/x86_64-linux
Ruby load path ($LOAD_PATH)
/home/payway/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/site_ruby/1.9.1
/home/payway/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/site_ruby/1.9.1/x86_64-linux
/home/payway/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/site_ruby
/home/payway/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/vendor_ruby/1.9.1
/home/payway/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/vendor_ruby/1.9.1/x86_64-linux
/home/payway/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/vendor_ruby
/home/payway/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1
/home/payway/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/x86_64-linux
Ruby loaded libraries ($LOADED_FEATURES)
enumerator.so
/home/payway/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/x86_64-linux/enc/encdb.so
/home/payway/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/x86_64-linux/enc/trans/transdb.so
/home/payway/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/x86_64-linux/rbconfig.rb
/home/payway/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/thread.rb
/home/payway/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/site_ruby/1.9.1/rubygems/compatibility.rb
/home/payway/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/site_ruby/1.9.1/rubygems/defaults.rb
/home/payway/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/site_ruby/1.9.1/rubygems/deprecate.rb
/home/payway/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/site_ruby/1.9.1/rubygems/errors.rb
/home/payway/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/site_ruby/1.9.1/rubygems/version.rb
/home/payway/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/site_ruby/1.9.1/rubygems/requirement.rb
/home/payway/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/site_ruby/1.9.1/rubygems/platform.rb
/home/payway/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/site_ruby/1.9.1/rubygems/basic_specification.rb
/home/payway/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/site_ruby/1.9.1/rubygems/stub_specification.rb
/home/payway/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/site_ruby/1.9.1/rubygems/util/stringio.rb
/home/payway/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/site_ruby/1.9.1/rubygems/specification.rb
/home/payway/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/site_ruby/1.9.1/rubygems/exceptions.rb
/home/payway/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_gem.rb
/home/payway/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/monitor.rb
/home/payway/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb
/home/payway/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/site_ruby/1.9.1/rubygems.rb
/usr/lib/ruby/vendor_ruby/phusion_passenger.rb
/usr/lib/ruby/vendor_ruby/phusion_passenger/constants.rb
/home/payway/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/x86_64-linux/etc.so
/home/payway/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/fileutils.rb
/home/payway/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/tmpdir.rb
/usr/lib/ruby/vendor_ruby/phusion_passenger/utils/tmpio.rb
/usr/lib/ruby/vendor_ruby/phusion_passenger/platform_info.rb
/usr/lib/ruby/vendor_ruby/phusion_passenger/platform_info/operating_system.rb
/home/payway/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/site_ruby/1.9.1/rubygems/path_support.rb
/home/payway/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb
/usr/lib/ruby/vendor_ruby/phusion_passenger/platform_info/ruby.rb
/usr/lib/ruby/vendor_ruby/phusion_passenger/platform_info/binary_compatibility.rb
/home/payway/.passenger/native_support/5.1.1/ruby-1.9.3-x86_64-linux/passenger_native_support.so
/usr/lib/ruby/vendor_ruby/phusion_passenger/native_support.rb
/home/payway/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/x86_64-linux/socket.so
/home/payway/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/socket.rb
/home/payway/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/x86_64-linux/pathname.so
/home/payway/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/pathname.rb
/usr/lib/ruby/vendor_ruby/phusion_passenger/ruby_core_enhancements.rb
/usr/lib/ruby/vendor_ruby/phusion_passenger/ruby_core_io_enhancements.rb
/home/payway/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/base64.rb
/usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb
/usr/lib/ruby/vendor_ruby/phusion_passenger/preloader_shared_helpers.rb
/usr/lib/ruby/vendor_ruby/phusion_passenger/public_api.rb
/usr/lib/ruby/vendor_ruby/phusion_passenger/debug_logging.rb
/home/payway/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/shellwords.rb
/usr/lib/ruby/vendor_ruby/phusion_passenger/utils/shellwords.rb
/usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb
/home/payway/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/x86_64-linux/fcntl.so
/usr/lib/ruby/vendor_ruby/phusion_passenger/message_channel.rb
/usr/lib/ruby/vendor_ruby/phusion_passenger/message_client.rb
/usr/lib/ruby/vendor_ruby/phusion_passenger/utils/native_support_utils.rb
/usr/lib/ruby/vendor_ruby/phusion_passenger/utils/unseekable_socket.rb
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb
/home/payway/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/x86_64-linux/stringio.so
/usr/lib/ruby/vendor_ruby/phusion_passenger/utils/tee_input.rb
/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb
/usr/lib/ruby/vendor_ruby/phusion_passenger/vendor/union_station_hooks_core/lib/union_station_hooks_core/version.rb
/usr/lib/ruby/vendor_ruby/phusion_passenger/vendor/union_station_hooks_core/lib/union_station_hooks_core.rb
/usr/lib/ruby/vendor_ruby/phusion_passenger/vendor/union_station_hooks_rails/lib/union_station_hooks_rails/version.rb
/usr/lib/ruby/vendor_ruby/phusion_passenger/vendor/union_station_hooks_rails/lib/union_station_hooks_rails.rb
This website is powered by Passenger®, a rock-solid, feature-rich
```

**Comment by CamJN** [comment] 2017-01-05 16:48
Have you made sure that you installed the rack gem in your chosen ruby?

**Comment by gonace** [comment] 2017-01-05 16:59
Hi
I've ensured that rack is installed (Using rack 1.4.7) in the gemset used, however you got me thinking and I installed rack globally just to check and then rack was loaded, but another gem now throws the same error.

So it seams that there is something weird with Passenger not using the gemset provided, any ideas?

**Comment by CamJN** [comment] 2017-01-05 17:00
ah you probably are setting the passenger_ruby to the ruby binary not the rvm shim. Run `passenger-config about ruby-command` to get the right path.

**Comment by gonace** [comment] 2017-01-05 17:03
It seems to be the right one:
```
passenger-config was invoked through the following Ruby interpreter:
  Command: /home/payway/.rvm/gems/ruby-1.9.3-p545@tulo-httpapi/wrappers/ruby
  Version: ruby 1.9.3p545 (2014-02-24 revision 45159) [x86_64-linux]
  To use in Apache: PassengerRuby /home/payway/.rvm/gems/ruby-1.9.3-p545@tulo-httpapi/wrappers/ruby
  To use in Nginx : passenger_ruby /home/payway/.rvm/gems/ruby-1.9.3-p545@tulo-httpapi/wrappers/ruby
  To use with Standalone: /home/payway/.rvm/gems/ruby-1.9.3-p545@tulo-httpapi/wrappers/ruby /usr/bin/passenger start
```
```
server {
        charset utf-8;
        listen 80 default_server;
        server_name 127.0.0.1 10.30.1.1;
        error_log /var/log/nginx/homer/error.log warn;
        access_log /var/log/nginx/homer/access.log;
        keepalive_timeout 300;
        client_max_body_size 4G;

        root /home/payway/current/apps/homer2/public;

        # Turn on Passenger
        passenger_enabled on;
        passenger_ruby /home/payway/.rvm/gems/ruby-1.9.3-p545@tulo-httpapi/wrappers/ruby;
        passenger_app_env azure_test;
        passenger_env_var TULO_ENV azure_test;
        passenger_friendly_error_pages on;

        # Union Station for Passenger
        union_station_support on;
        union_station_key nl41zru6va74qe68hgp1oj0rw4k0dhk;
}
```

**Comment by CamJN** [comment] 2017-01-05 17:13
There seems to be a problem with your ruby install, it reports `ruby_version = 1.9.1` but the path suggests you installed `1.9.3`. you may want to reinstall and see if that helps.

**Comment by gonace** [comment] 2017-01-05 17:22
Now that's strange, I've experiencing the same problem on two servers which have the same "/usr/bin/env" output.

**Comment by gonace** [comment] 2017-01-05 21:22
Hi
So there have to be something else at wrong here, I've manually installed the gems to the @global gemset and now it runs just fine, any ideas why it seems that Passenger uses  the wrong gemset?

The applications it self uses the correct gemset, but Passenger is somehow not.

**Comment by CamJN** [comment] 2017-01-05 21:42
Could you elaborate on what you mean when you say "The applications it self uses the correct gemset, but Passenger is somehow not."? Thanks.

**Comment by gonace** [comment] 2017-01-05 21:51
Well I'm sure I just stated that badly, what I meant was that if I run the application in nginx with Passenger it seems it doesn't use the correct gemset. But if I run it with Unicorn or Foreman it loads with the correct gemset.

**Comment by OnixGH** [comment] 2017-01-05 21:52
And if you run it with passenger standalone? (`passenger start`)?

**Comment by gonace** [comment] 2017-01-05 22:02
The exact same error is thrown when running Passenger standalone.

Regards

**Comment by OnixGH** [comment] 2017-01-05 22:12
Can you try:
```
rvm get head
rvm reload
```

**Comment by gonace** [comment] 2017-01-05 22:23
Yes, just tried that and I'm getting the same error still.

**Comment by OnixGH** [comment] 2017-01-05 22:51
Hmm, I just tried an app with the same Ruby (1.9.3) + Rack (1.4.7) version as you, with gems in the local gemset (not global) and Passenger works without a problem after those commands (both the Nginx and Standalone version).

Basically Passenger just executes whatever Ruby you point it to, with a default or specified user/group. Problems are usually caused by something about an (rvm/gem/etc.) install not being in order, or a user / group / path type issue.

**Comment by CamJN** [comment] 2017-01-05 22:56
It looks like your user isn't in the rvm group, which might be the problem.

**Comment by gonace** [comment] 2017-01-06 08:20
I've tried another app which runs a Ruby 2.3 and that worked, however the installation of Ruby 2.3 is done the same way as 1.9.3 on a different machine. 

The rvm installation is a single-user installation, so the rvm group is not used or created during the installation, should I try installing rvm in multie-user mode? would that make sense?

**Comment by CamJN** [comment] 2017-01-06 15:23
If ruby 2.3 works then that strongly points to an issue with rvm's ruby 1.9.3. Do you install precompiled binaries from rvm or build from source?

**Comment by gonace** [comment] 2017-01-06 17:21
I install ruby from rvm, I'll dig intro if it's a possibility on upgrading to Ruby 2.3 after the weekends.

**Comment by CamJN** [comment] 2017-01-06 17:28
I know you install from rvm, but rvm has two modes of operation when installing rubies. It tries to download a prebuilt binary for your platform, but if one isn't available then it builds from source. Since you had the same problem on two boxes with the same version of ruby but not with another version, that sounds like it may be an issue with the prebuilt ruby 1.9.3 that rvm provides. You can force a compile using `rvm reinstall --disable-binary $version`.

**Comment by gonace** [comment] 2017-01-07 09:20
Oh sorry, I misread, that is a good point! I'll try that, thanks.

**Comment by gonace** [comment] 2017-01-07 10:19
Is there a way to specify the Gemfile path? So if multiple application share the same Gemfile outside the application directory?

**Comment by OnixGH** [comment] 2017-01-09 11:04
@gonace Our [Community support forum](https://groups.google.com/forum/#!forum/phusion-passenger) is the place for configuration questions. This issue report doesn't appear to be a problem with Passenger, so I'll close it.

**Closed by OnixGH** 2017-01-09 11:04 UTC
Labels: SupportCentral
