### ISSUE TITLE
Flying Passenger erroneously spawns multiple preloaders

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#1443] opened 2015-03-19 11:22 UTC
A user has reported that Passenger 5.0.4 spawns many preloader processes.

```
---------------------------------------
Version: 5.0.4
Date   : 2015-03-19 12:06:43 +0100
------------- Apache processes -------------
*** WARNING: The Apache executable cannot be found.
Please set the APXS2 environment variable to your 'apxs2' executable's filename, or set the HTTPD environment variable to your 'httpd' or 'apache2' executable's filename.


--------- Nginx processes ----------
PID   PPID  VMSize    Private  Name
------------------------------------
334   1     123.7 MB  0.7 MB   nginx: master process /usr/sbin/nginx
6414  334   123.7 MB  1.0 MB   nginx: worker process
6415  334   123.7 MB  1.2 MB   nginx: worker process
6416  334   123.7 MB  0.7 MB   nginx: worker process
6417  334   123.7 MB  0.7 MB   nginx: worker process
### Processes: 5
### Total private dirty RSS: 4.41 MB


----- Passenger processes ------
PID   VMSize     Private   Name
--------------------------------
3450  4.0 MB     0.1 MB    supervise flying-passenger
6104  100.8 MB   6.8 MB    /usr/bin/ruby1.9.3p194 /usr/bin/flying-passenger --instance-registry-dir=/var/run/flying-passenger --socket-file=/var/run/flying-passenger.sock --log-file=/var/log/flying-passenger.log --pid-file=/var/run/flying-passenger.pid --max-pool-size=6
6112  342.6 MB   0.8 MB    PassengerAgent watchdog
6115  2144.2 MB  10.6 MB   PassengerAgent server
6120  213.9 MB   0.9 MB    PassengerAgent logger
6698  312.1 MB   82.9 MB   Passenger AppPreloader: /export/www/yyyy/ruby
7259  419.6 MB   109.4 MB  Passenger AppPreloader: /export/www/xxx/ruby
7310  421.3 MB   111.1 MB  Passenger AppPreloader: /export/www/xxx/ruby
7316  421.1 MB   111.0 MB  Passenger AppPreloader: /export/www/xxx/ruby
7322  421.2 MB   111.1 MB  Passenger AppPreloader: /export/www/xxx/ruby
7325  421.3 MB   111.1 MB  Passenger AppPreloader: /export/www/xxx/ruby
7334  421.3 MB   111.2 MB  Passenger AppPreloader: /export/www/xxx/ruby
7342  421.1 MB   111.0 MB  Passenger AppPreloader: /export/www/xxx/ruby
7536  421.2 MB   111.1 MB  Passenger AppPreloader: /export/www/xxx/ruby
7545  421.3 MB   111.1 MB  Passenger AppPreloader: /export/www/xxx/ruby
7557  421.3 MB   111.1 MB  Passenger AppPreloader: /export/www/xxx/ruby
7559  421.0 MB   110.9 MB  Passenger AppPreloader: /export/www/xxx/ruby
7570  421.3 MB   111.1 MB  Passenger AppPreloader: /export/www/xxx/ruby
7581  421.0 MB   111.0 MB  Passenger AppPreloader: /export/www/xxx/ruby
7685  421.0 MB   111.0 MB  Passenger AppPreloader: /export/www/xxx/ruby
7702  421.3 MB   111.2 MB  Passenger AppPreloader: /export/www/xxx/ruby
7711  421.2 MB   111.1 MB  Passenger AppPreloader: /export/www/xxx/ruby
7720  421.2 MB   111.1 MB  Passenger AppPreloader: /export/www/xxx/ruby
7729  421.2 MB   111.1 MB  Passenger AppPreloader: /export/www/xxx/ruby
7752  421.2 MB   111.1 MB  Passenger AppPreloader: /export/www/xxx/ruby
7849  421.1 MB   111.0 MB  Passenger AppPreloader: /export/www/xxx/ruby
7868  421.1 MB   110.9 MB  Passenger AppPreloader: /export/www/xxx/ruby
7897  421.3 MB   111.1 MB  Passenger AppPreloader: /export/www/xxx/ruby
7906  421.3 MB   111.1 MB  Passenger AppPreloader: /export/www/xxx/ruby
7929  421.3 MB   111.1 MB  Passenger AppPreloader: /export/www/xxx/ruby
7940  421.1 MB   111.0 MB  Passenger AppPreloader: /export/www/xxx/ruby
8052  421.2 MB   111.0 MB  Passenger AppPreloader: /export/www/xxx/ruby
8112  421.3 MB   111.1 MB  Passenger AppPreloader: /export/www/xxx/ruby
8121  421.1 MB   111.0 MB  Passenger AppPreloader: /export/www/xxx/ruby
8147  421.4 MB   111.2 MB  Passenger AppPreloader: /export/www/xxx/ruby
8150  421.1 MB   111.0 MB  Passenger AppPreloader: /export/www/xxx/ruby
8187  421.2 MB   111.1 MB  Passenger AppPreloader: /export/www/xxx/ruby
### Processes: 37
### Total private dirty RSS: 3543.68 MB
```

This user is using Flying Passenger. Nginx config:

```
passenger_root                  /usr/lib/ruby/vendor_ruby/phusion_passenger/locations.ini;
passenger_ruby                  /usr/bin/ruby;
passenger_fly_with              /var/run/flying-passenger.sock;
passenger_instance_registry_dir /var/run/flying-passenger;
passenger_min_instances         2;
passenger_max_pool_size         5;
passenger_concurrency_model     thread;
rails_env                       development;
```

Flying Passenger invocation:

```
exec /usr/bin/ruby1.9.3p194 /usr/bin/flying-passenger \
    --instance-registry-dir=/var/run/flying-passenger \
    --socket-file=/var/run/flying-passenger.sock \
    --log-file=/var/log/flying-passenger.log \
    --pid-file=/var/run/flying-passenger.pid \
    --max-pool-size=6
```

**Comment by Daniel304** [comment] 2015-03-24 11:29
It seems the problems are with flying passenger... just by commenting passenger_fly_with should nginx stop flying passenger and revert to the normal passenger if i am correct.
After doing this the load times went down from sometimes 21 minutes to mere seconds.

**Comment by Daniel304** [comment] 2015-03-27 14:06
just had another incident with the same problem however I am not running flying passenger anymore. however starting an application can still spawn 87 processes:

passenger-status
Version : 5.0.5
Date    : 2015-03-27 15:03:58 +0100
Instance: MThSle8h (nginx/1.6.2 Phusion_Passenger/5.0.5)

----------- General information -----------
Max pool size : 5
Processes     : 5
Requests in top-level queue : 0

----------- Application groups -----------
/export/www/kpn_bis/ruby/public/assets/jquery-ui/draggable.css/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/jquery-ui/slider.css/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/jquery-ui/tooltip.css/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/oxyma_kpncep/application.js/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0
  * PID: 22524   Sessions: 0       Processed: 1       Uptime: 4m 56s
    CPU: 0%      Memory  : 46M     Last used: 4m 56s ago

/export/www/kpn_bis/ruby/public/assets/jquery-ui/button.js/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/oxyma_framework/application.css/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/jquery-ui/core.js/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/jquery-ui/tooltip.js/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/jquery-ui/selectable.css/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/vf_nba/ruby/public (development)#default:
  App root: /export/www/vf_nba/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/jquery-ui/effect-clip.js/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/jquery-ui/selectmenu.css/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/bootstrap/alert.js/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/jquery-ui/autocomplete.css/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/jquery-ui/effect-bounce.js/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/bootstrap/affix.js/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/oxyma_erwinro/ruby/public (development)#default:
  App root: /export/www/oxyma_erwinro/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/bootstrap/button.js/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/telfort_gratispl/ruby/public (development)#default:
  App root: /export/www/telfort_gratispl/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/bootstrap/collapse.js/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/bootstrap/scrollspy.js/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/bootstrap-sprockets.js/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0
  * PID: 22506   Sessions: 0       Processed: 1       Uptime: 4m 57s
    CPU: 0%      Memory  : 46M     Last used: 4m 57s ago

/export/www/kpn_bis/ruby/public/assets/bootstrap/modal.js/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/bootstrap/tooltip.js/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/jquery-ui/autocomplete.js/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/jquery-ui/effect-fade.js/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/jquery-ui/effect-puff.js/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/jquery-ui/effect-pulsate.js/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/jquery-ui/effect-transfer.js/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/jquery-ui/progressbar.js/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/jquery-ui/spinner.css/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/jquery-ui/tabs.css/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/jquery-ui/base.css/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/jquery-ui/sortable.js/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/jquery.js/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/jquery-ui/dialog.js/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/jquery-ui/effect-blind.js/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/jquery-ui/slider.js/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/jquery-ui/datepicker.js/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/jquery-ui/effect-explode.js/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/jquery-ui/effect-scale.js/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/bootstrap/glyphicons-halflings-regular.woff/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0
  * PID: 22534   Sessions: 0       Processed: 1       Uptime: 4m 55s
    CPU: 0%      Memory  : 45M     Last used: 4m 55s ago

/export/www/kpn_bis/ruby/public/assets/jquery-ui/menu.css/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/jquery-ui/dialog.css/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/jquery-ui/menu.js/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/jquery-ui/effect-shake.js/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/bootstrap/dropdown.js/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/jquery-ui/resizable.css/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/jquery-ui/button.css/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/bootstrap/carousel.js/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/bootstrap/transition.js/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/jquery-ui/sortable.css/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/jquery-ui.css/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/jquery-ui/droppable.js/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/jquery-ui/resizable.js/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/jquery-ui/position.js/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/telfort_bereikb/ruby/public (development)#default:
  App root: /export/www/telfort_bereikb/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/jquery-ui/effect.js/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/jquery-ui/effect-drop.js/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/bootstrap/tab.js/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/oxyma_framework/application.js/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0
  * PID: 22514   Sessions: 0       Processed: 1       Uptime: 4m 56s
    CPU: 0%      Memory  : 45M     Last used: 4m 56s ago

/export/www/kpn_bis/ruby/public/assets/jquery-ui/effect-fold.js/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/jquery-ui/theme.css/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/jquery-ui/effect-size.js/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/jquery-ui.js/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/jquery-ui/all.css/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/jquery-ui/ui-bg_flat_75_ffffff_40x100.png/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/jquery-ui/widget.js/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/oxyma_showcase/ruby/public (development)#default:
  App root: /export/www/oxyma_showcase/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/jquery-ui/progressbar.css/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/jquery-ui/spinner.js/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/jquery-ui/effect-highlight.js/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/jquery-ui/effect-slide.js/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/jquery-ui/selectable.js/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/bootstrap/popover.js/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0
  * PID: 22494   Sessions: 0       Processed: 1       Uptime: 4m 57s
    CPU: 0%      Memory  : 46M     Last used: 4m 57s ago

/export/www/kpn_bis/ruby/public/assets/jquery-ui/accordion.js/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/jquery-ui/accordion.css/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/jquery-ui/datepicker.css/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/oxyma_framework/oxyma.css/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/admin/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/admin/kpncep/MAM1662_BISmigratie/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/jquery-ui/mouse.js/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/jquery-ui/core.css/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/jquery-ui/tabs.js/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/jquery-ui/draggable.js/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/jquery-ui/selectmenu.js/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/jquery_ujs.js/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

/export/www/kpn_bis/ruby/public/assets/oxyma_kpncep/application.css/bbinternet (development)#default:
  App root: /export/www/kpn_bis/ruby
  Requests in queue: 0

**Comment by Daniel304** [comment] 2015-03-27 14:21
problem is reproducable when having:
config.assets.debug = true
when on 
config.assets.debug = false
there is no problem what so ever.

**Comment by OnixGH** [comment] 2015-05-08 09:55
@Daniel304 jquery-ui and to a lesser extent twitter-bootstrap result in a lot of css and js links in the page if `config.assets.debug = true`, which in turn probably results in many more simultaneous connections on page load. With `config.assets.debug = false`, the linked assets are merged so my takeaway is that it's somehow related to the amount of simultaneous connections (and not specifically those gems or the debug setting).

Unfortunately we haven't been able to reproduce your issue so far. In my test setup(*) mimicking your setup, it performs as expected so far.

Did the preloader issue start or get worse when you lowered the max-pool-size to 6 (from 64)? Are there any other passengers running on the same server? The trace shows 2 (rails?) apps, what happened before this, did you just visit the 2 apps one by one in sequence? The one with the repeating preloaders first or second? Any other hints? Is it still occurring with 5.0.7?

(*) I have this test setup on Ubuntu:
- 9 rails apps, dev mode with config.assets.debug = true, jquery-ui and twitter-bootstrap gems (included through application.css, application.js and working)
- flying-passenger 5.0.4
- ruby 1.9.3 (p551) (rails 4.2.1) 
Simultaneous wgets (--prerequisites etc.) to the apps give me the expected behavior (1 preloader per app.).

**Comment by Daniel304** [comment] 2015-05-12 08:20
At this moment we are not using flying passenger... Hopefully in the coming weeks we will have the opportunity to try and test it again... for now passenger works perfectly...

**Comment by OnixGH** [comment] 2015-08-08 14:24
@Daniel304 any news on this one?

**Comment by Daniel304** [comment] 2015-11-12 10:54
I cannot reproduce this anymore.

**Closed** 2015-11-12 11:23 UTC
Labels: CannotReproduce, EnterpriseCustomer
