### ISSUE TITLE
processes get stuck and passenger 5.0.7 stops serving requests

### ISSUE THREAD

**Issue by bpang** [phusion/passenger#1512] opened 2015-05-15 01:17 UTC
_Summarizing note about this issue by FooBarWidget:_

There are 4 people posting in this thread. But as it turns out, not all of these people are having the same issue. Here's what we currently know:

 * bpang's issue is still unknown.
 * michaelrigart's's issue is caused by Passenger not correctly handling nil response body objects. This will be fixed soon.
 * vddgil's issue is unrelated. It was caused by a memcached problem and was not related to Passenger.
 * rwilsonncsa's's issue is also unrelated. Turns out to be a problem in his own application.

------

_Original issue report follows:_

Recently upgraded to 5.0.7 running nginx 1.8.0 and a Rails 2.3.18 app on CentOS 6.5 / 2.6.32-431.11.2.el6.x86_64.  It will run fine for a while and then under load, the pools get stuck with 1 session per pool and the request in queue piles up and the server stop serving requests.  I rolled back to using 4.0.53 and nginx 1.6.3 which has been stable for us.

```
./passenger-status
Version : 5.0.7
Date    : Thu May 14 16:44:14 -0700 2015
Instance: 20IaTTq9 (nginx/1.8.0 Phusion_Passenger/5.0.7)

----------- General information -----------
Max pool size : 6
Processes     : 6
Requests in top-level queue : 0

----------- Application groups -----------
/home/trekaroo/current/public#default:
  App root: /home/trekaroo/current
  Requests in queue: 1011
  * PID: 23207   Sessions: 1       Processed: 6177    Uptime: 1h 41m 5s
    CPU: 16%     Memory  : 420M    Last used: 25m 15s a
  * PID: 23214   Sessions: 1       Processed: 1805    Uptime: 1h 41m 5s
    CPU: 4%      Memory  : 310M    Last used: 25m 19s a
  * PID: 23221   Sessions: 1       Processed: 367     Uptime: 1h 41m 5s
    CPU: 1%      Memory  : 223M    Last used: 25m 2s ag
  * PID: 26242   Sessions: 1       Processed: 47      Uptime: 1h 3m 55s
    CPU: 0%      Memory  : 115M    Last used: 25m 18s a
  * PID: 28866   Sessions: 1       Processed: 1       Uptime: 25m 22s
    CPU: 0%      Memory  : 93M     Last used: 25m 16s ago
  * PID: 28878   Sessions: 1       Processed: 8       Uptime: 25m 13s
    CPU: 0%      Memory  : 110M    Last used: 25m 3s ago
```

**Comment by OnixGH** [comment] 2015-05-15 08:22
Thanks for reporting. Unfortunately, while the trace does indicate an issue, we cannot debug it further with the status information posted. We need the output of this command while the server appears stuck:
`passenger-status --show=requests`

**Comment by OnixGH** [comment] 2015-05-15 09:29
P.S. please check that it's not your app freezing up. It could also be the cause of this.

See also: http://old.blog.phusion.nl/2012/09/21/the-right-way-to-deal-with-frozen-processes-on-unix/

**Comment by michaelrigart** [comment] 2015-05-18 19:43
Hey,

it seems I'm experiencing the same problem. The app in question is a simple Rails application. After switching from passenger 4 to the newest release,  requests start to get queued. 

The output can be found here: https://gist.github.com/michaelrigart/6bafa1d34953e3abde63

**Comment by OnixGH** [comment] 2015-05-19 10:16
@michaelrigart Can you post the output of both `passenger-status` as well as `passenger-status --show=requests`? 

Is there anything happening in the error logs? Does it happen right away or after some time?

**Comment by michaelrigart** [comment] 2015-05-19 10:20
I'll get back to you tomorrow on this. I reverted back to v4 at this moment.
I'll have time tomorrow to setup a staging to do further testing on v5. 

The error logs do not show any errors ( not on the application level, nor nginx ), and it doesn't happen right away. In my case, it took a couple of minutes before one of the projects started to "hang". But once it was queueing requests, I was under the impression it started queueing them all. 

But again, I will provide you with more details tomorrow once I have setup a staging environment on v5.

**Comment by bpang** [comment] 2015-05-19 21:00
I had a similar experience.  I haven't seen it in our staging environment and I've already rolled back our production environment.  I'll throw some load at staging to see if I can try and reproduce the issue.

**Comment by vddgil** [comment] 2015-05-22 07:04
Hello,

I had a similar experience with 5.0.8 with Ruby on Rails 4.2.0.

Here is the passenger-status command output: https://gist.github.com/vddgil/14521b7f812fb26294c5

Here is the passenger-status --show=requests command output: https://gist.github.com/vddgil/81891785e8ee918d19a7

It seems that all stuck processes are waiting for an image. I manage my images with [dragonfly](https://github.com/markevans/dragonfly).

Everything was working fine before with unicorn.

Thanks!

**Comment by OnixGH** [comment] 2015-05-22 07:58
@vddgil dis there anything noteworthy in the error log?

**Comment by FooBarWidget** [comment] 2015-05-22 09:58
@michaelrigart  @vddgil From what I see in your log files, all stuck requests have things in common:

1. The application has already sent headers.
2. At the same time, the application didn't even send 1 byte of body. Passenger keeps waiting for this body forever.

@vddgil All your stuck requests are for /media/*. Can you tell me a bit about how the /media/* endpoint in your app is implemented? How do you generate a response? Are you using anything like `send_file`, X-Accel-Redirect or X-Sendfile? Are you able to reproduce this problem in a consistent manner? How often did it occur?

@michaelrigart Your case is a bit more mysterious. You have a variety of endpoints that get stuck. Are you able to reproduce this problem in a consistent manner? How often did it occur?

**Comment by vddgil** [comment] 2015-05-25 06:46
@FooBarWidget 

1. My `/media/*` endpoint is an endpoint that respond with an image. This endpoint is implemented by the gem dragonfly [dragonfly](https://github.com/markevans/dragonfly)
2. I have this in my rails production.rb: `config.action_dispatch.x_sendfile_header = 'X-Accel-Redirect'`

Yes, as soon i visit this endpoint, one process get stuck, a reload the page and another get stuck too. I can repeat the operation easily until all processes get stuck.

As i said before, everything was working fine with my unicorn config. But i really want to move to passenger :)

Thanks !

**Comment by michaelrigart** [comment] 2015-05-27 13:47
Sorry for the delay. I finally got around creating the specific staging environment. I still can reproduce this in 5.0.8.

I'm able to reproduce this on a regular basis. The apps take a few requests, and then all of the sudden, some apps just stop responding and the requests get queued. 
After I restart nginx, everything works find again for a few requests and then the same thing happens over again.

I must say, during the staging setup, I started messing around with assets and it seems that passenger starts to choke when nginx wants to serve assets that are not present, but that was just an assumption of mine. 

passenger-status
https://gist.github.com/michaelrigart/f36538f378cac6156b26

passenger-status --show=requests
https://gist.github.com/michaelrigart/258adcf52ba3fe6de344

**Comment by rwilsonncsa** [comment] 2015-05-27 18:22
Similar issue on 5.0.7.  We have "config.action_dispatch.x_sendfile_header = 'X-Accel-Redirect'" already commented out.

passenger-status
https://gist.github.com/rwilsonncsa/19bb74104454e88490cb

passenger-status --show=requests
https://gist.github.com/rwilsonncsa/9e2b1bef89c7f149eb2e

**Comment by OnixGH** [comment] 2015-05-28 10:03
@rwilsonncsa your issue looks different. According to the traces, passenger is waiting for your application to send response headers (`"app_response_http_state" : "PARSING_HEADERS"`), while in the other traces the response headers were successfully received (`"app_response_http_state" : "PARSING_BODY_WITH_LENGTH"`).

Since your app hasn't sent response headers, it is likely still busy doing something. Most of the stuck paths refer to `"..../send_email"`, maybe an email send process is hanging? You can use the blog guide I mentioned at the beginning of this thread to debug frozen processes.

**Comment by OnixGH** [comment] 2015-05-28 11:00
@vddgil can you see if the workaround @michaelrigart posted also works for you? (commenting out `config.action_dispatch.x_sendfile_header = 'X-Accel-Redirect'`)

@michaelrigart @vddgil your traces are indeed similar: passenger waiting for body content (in one case with `content-length` encoding, in the other case with `chunked` encoding) that is apparently never sent.

Previously we saw this issue occurring with the `X-Accel-Redirect` flag because content is not supposed to be sent, but we changed passenger to ignore the content when that flag is seen. Could you attach or email a logfile made with `passenger_log_level 7;` so we can see what headers are actually being returned? Maybe we missed one or there is some kind of flow not covered yet by the previous fix.

**Comment by michaelrigart** [comment] 2015-05-28 11:53
@OnixGH you can find the error log at: http://www.netronix.be/error_log.tar

**Comment by OnixGH** [comment] 2015-05-28 12:02
@michaelrigart downloaded, thanks!

**Comment by vddgil** [comment] 2015-05-28 12:57
Hello,

I disabled the X-Accel-Redirect header and the problem is still happening.

Log file with log level 7: 
https://dl.dropboxusercontent.com/u/12677052/passenger.log.zip

passenger-status
https://gist.github.com/vddgil/4ae3fbbe4d218bcccd14

passenger-status --show=requests
https://gist.github.com/vddgil/44d2d7554294eb7070da

**Comment by rwilsonncsa** [comment] 2015-05-28 13:50
@OnixGH Thanks for your reply. I came to a similar conclusion. You are just a ton faster at figuring things out. We downgraded passenger to 4.0.59 and still had the issue. Clearly the issue lies someplace else.

**Comment by OnixGH** [comment] 2015-05-28 16:44
@michaelrigart in your trace I see two responses from the app getting stuck. In both cases the app sends a redirect (301) response, with "Transfer-Encoding: chunked". 
```
GET / HTTP/1.1
Host: nickdemeester.be
..
HTTP/1.1 301 Whatever
Location: http://www.nickdemeester.be/nl/home.html
Transfer-Encoding: chunked
```
```
GET /api/get_network_items/all.json HTTP/1.1
Host: www.cultuurgevoeligejeugdhulp.be
..
HTTP/1.1 301 Whatever
Location: http://www.cultuurgevoeligejeugdhulp.be/nl/get_network_items/all.html
Transfer-Encoding: chunked
```
Do you know if the app actually supplies a body for these redirects? None of the other redirects in the trace have it. Or is it an empty body?

In either case it doesn't seem to have anything with `X-Accel-Redirect` btw.

**Comment by OnixGH** [comment] 2015-05-28 16:51
@vddgil that's a really helpful log with the status next to it, thanks.

The main thing I see is that hundreds of images are served fine, but the media that get stuck are exactly the biggest ones, >1 MB:
```
3.087.546 "tuin.jpg" (x2)
2.874.230 "P8270917.JPG"
1.128.227 "DSCF2108.JPG" (x2)
```
For those, the content from your application doesn't arrive to passenger and it keeps waiting. Are you aware of any component in your middleware that might have a 1 MB limit? Maybe rack/cache or something?

**Comment by vddgil** [comment] 2015-05-28 17:01
@OnixGH Indeed, i have a rack-cache in my application only for my images. It's a rails 4 app and i followed this documentation to activate the cache: http://markevans.github.io/dragonfly/rails/#caching

How can i configure this limit ? Maybe i can try to disable the cache ?

Again, it was working fine with unicorn.

**Comment by OnixGH** [comment] 2015-05-28 17:11
@vddgil I don't know if you have memcached behind it but then [this stackoverflow answer](http://stackoverflow.com/questions/17656999/how-to-cache-files-over-1mb-with-rack-cache-on-heroku) might help.

I don't know much about unicorn's internals, but it's not uncommon for hidden issues to emerge when switching servers. In any case we're taking a good look at the application to passenger transfer scripts now that we know roughly where to look.

**Comment by michaelrigart** [comment] 2015-05-28 17:27
@OnixGH there is no body for the redirect. It's a basic redirect made from a rack middleware:
 [301, { 'Location' => "http://www.#{request.host}#{request.fullpath}"}]

It happens when you enter the application without a path given.

Anyway, I have created a new error log ( http://www.netronix.be/error_log.tar ) . This time I have disabled the pre-start and visited the applications giving a path, so the redirect does not occur. The same problem still happens. At a given moment, one application stopped handling requests. The application that stopped during my tests now is: www.cultuurgevoeligejeugdhulp.be ( if that narrows it down for you ). 
But in the end, it is not always the same application

**Comment by vddgil** [comment] 2015-05-28 17:55
@OnixGH 
Indeed, i have memcache behind and it's working with the monkey patch. 
Basically, it disable the cache for file > 1MO.

Thanks a lot for your answers !!

**Comment by FooBarWidget** [comment] 2015-05-28 17:55
@michaelrigart OnixGH and I have been able to determine that there is a bug in Passenger w.r.t. handling that kind of Rack response. Can I ask you which Rack middleware that response came from? Is it your own middleware? Or does it come from some gem?

**Comment by OnixGH** [comment] 2015-05-28 18:16
@vddgil :+1: 

@michaelrigart actually your second trace still contains the same 301's with zero body chunked replies for `GET /api/get_network_items/all.json` (for the app you mention). This is good, because we might be able to fix that particular case, like @FooBarWidget says.

**Comment by michaelrigart** [comment] 2015-05-28 18:20
@FooBarWidget @OnixGH  This is our own middleware, so it does not come from a gem. 
Let me know if you want me to test something out.

**Comment by FooBarWidget** [comment] 2015-05-29 12:52
@bpang @michaelrigart I've pushed a fix to the GH-1512 branch. Could you test whether it fixes your issues?

@michaelrigart In your case, you were returning an invalid response object. The Rack specification states that the response body must always be an object that responds to `#each`. So it may not be nil. Passenger wasn't handling nil objects correctly, so the connection got stuck. In any case, we believe that it should not be possible for the app to make the connection stuck, even if it was the app's fault. I've introduced extra checks in the GH-1512 branch to handle nil response objects.

**Comment by michaelrigart** [comment] 2015-05-29 13:34
@FooBarWidget seems the problem stops occurring on the GH-1512 branch.
Will fix this on the application side as well. In the mean time, I'll keep the tests running and get back if I see any changes.

**Comment by michaelrigart** [comment] 2015-05-29 14:00
I fixed the faulty redirects in the application and tested again against the current 5.0.8 release. I can confirm that the problem occurred due to the faulty redirects, since the requests don't get stuck anymore after fixing the empty response bodies.

**Comment by FooBarWidget** [comment] 2015-05-29 14:22
Ok, good. Once I have received feedback from @bpang I can close this issue.

**Comment by bpang** [comment] 2015-05-30 08:52
@FooBarWidget I have not been able to reproduce the issue in our staging environment, but it was similarly returning a nil response body.  I think you can close this one for now.  Thanks!

**Closed** 2015-05-30 09:48 UTC
Labels: NeedsFeedback, Priority/Critical
