### ISSUE TITLE
Variables passed to passenger_user directive are interpreted as strings

### ISSUE THREAD

**Issue by dannykopping** [phusion/passenger#2024] opened 2018-01-30 14:21 UTC
**Question 1: What is the problem?**
- What is the expected behavior?

Like most other nginx directives, it should accept a variable

- What is the actual behavior?

The directive interprets the variable as a string literal

- How can we reproduce it? Please try to provide a sample application (or Virtual Machine) demonstrating the issue. Otherwise, if we can't reproduce it, we might have to ask you a number of followup questions or run certain commands to try and figure out the problem.

In a location block, set `passenger_user` to a variable.

**Question 2: Passenger version and integration mode**:
- For example: open source 5.0.26 standalone; enterprise 5.0.21/nginx

```
# passenger-status
Using /usr/local/rvm/gems/ruby-2.1.9
Version : 5.1.5
Date    : 2018-01-30 14:18:43 +0000
Instance: JZgnWDsq (nginx/1.10.3 Phusion_Passenger/5.1.5)
```

**Question 3: OS or Linux distro, platform (including version)**:
- For example: Debian 8, x86_64 or OS X 10.10 Yosemite, x86_64

```
# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial
```

**Question 4: Passenger installation method**:

Your answer:
[ ] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[ ] Phusion APT repo
[ ] Phusion YUM repo
[ ] OS X Homebrew
[ ] source tarball
[ ] Other, please specify:
Docker: https://github.com/phusion/passenger-docker

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
- For example: Ruby 2.3.0, RVM, Rails 5.0.0; Node.js 4.0.0 with Express 4.13.4

```
# ruby -v
ruby 2.1.9p490 (2016-03-30 revision 54437) [x86_64-linux]
```

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
- For example: Heroku, Amazon Container Services, Docker 1.9 with an image based on passenger-docker

Docker: https://github.com/phusion/passenger-docker

**Question 7: Anything else about your setup that we should know?**

---

We strive for quality and appreciate you taking the time to submit a report! Please note that if you want guaranteed response times and priority issue support we encourage you to join our [enterprise customer](https://www.phusionpassenger.com/enterprise) base. They also provide us with the means to continue our high level of open source support!

**Comment by CamJN** [comment] 2018-01-30 16:35
Closing as a duplicate of #1779

**Closed by CamJN** 2018-01-30 16:35 UTC
