### ISSUE TITLE
Massive amount of error messages on load testing passenger application

### ISSUE THREAD

**Issue by mitomm** [phusion/passenger#1897] opened 2016-11-24 16:52 UTC
Hi everybody.

When I'm load testing my passenger application, I see the following two error messages inside the passenger log files:

```
[ 2016-11-24 17:12:14.0971 2814/7f4e16bfd700 Ser/Server.h:994 ]: [Client 2-72504] Disconnecting client with error: application did not send a complete response
[ 2016-11-24 17:12:14.1204 2814/7f4e161fc700 age/Cor/Con/ForwardResponse.cpp:189 ]: [Client 3-72503] Application sent EOF before finishing response body: 42910 bytes already read, 42911 bytes expected
[ 2016-11-24 17:12:14.1205 2814/7f4e161fc700 Ser/Server.h:994 ]: [Client 3-72503] Disconnecting client with error: application did not send a complete response
[ 2016-11-24 17:12:14.1207 2814/7f4e157fb700 age/Cor/Con/ForwardResponse.cpp:189 ]: [Client 4-72504] Application sent EOF before finishing response body: 42910 bytes already read, 42911 bytes expected
[ 2016-11-24 17:12:14.1207 2814/7f4e157fb700 Ser/Server.h:994 ]: [Client 4-72504] Disconnecting client with error: application did not send a complete response
[ 2016-11-24 17:12:14.1250 2814/7f4e175fe700 age/Cor/Con/ForwardResponse.cpp:189 ]: [Client 1-72504] Application sent EOF before finishing response body: 42910 bytes already read, 42911 bytes expected
[ 2016-11-24 17:12:14.1250 2814/7f4e175fe700 Ser/Server.h:994 ]: [Client 1-72504] Disconnecting client with error: application did not send a complete response
```

AND

```
[ 2016-11-24 16:25:26.7053 2814/7f4de7fff700 Ser/AcceptLoadBalancer.h:144 ]: Cannot accept client: Too many open files (errno=24). Stop accepting clients for 3 seconds.
2016/11/24 16:25:28 [error] 2842#0: *509941 connect() to unix:/tmp/passenger.KTGPxxi/agents.s/core failed (11: Resource temporarily unavailable) while connecting to upstream, client: 127.0.0.1, server: _, request: "GET /salon/wunderhaar HTTP/1.1", upstream: "passenger:unix:/tmp/passenger.KTGPxxi/agents.s/core:", host: "XXXX"
2016/11/24 16:25:28 [error] 2842#0: *509942 connect() to unix:/tmp/passenger.KTGPxxi/agents.s/core failed (11: Resource temporarily unavailable) while connecting to upstream, client: 127.0.0.1, server: _, request: "GET /salon/wunderhaar HTTP/1.1", upstream: "passenger:unix:/tmp/passenger.KTGPxxi/agents.s/core:", host: "XXXX"

...


```

Setup:
- open source Phusion_Passenger 5.0.30 in Standalone Mode (behind a NGINX reverse proxy)
- Node.js 6.9.1
- OS Linux 14.04

Thanks for any help.

**Comment by OnixGH** [comment] 2016-11-24 16:58
`Cannot accept client: Too many open files (errno=24).` looks like a configuration issue (ulimit too low). See for example this [ulimit option](https://www.phusionpassenger.com/library/config/standalone/reference/#--core-file-descriptor-ulimit-core_file_descriptor_ulimit)

Btw. if you're not sure it's an issue caused by Passenger it's best to ask on the [Community support forum](https://groups.google.com/forum/#!forum/phusion-passenger). We get a lot of issue reports that are not passenger issues here :).

**Comment by mitomm** [comment] 2016-11-24 17:42
Thanks for the quick reply. 

Alright, I'll use the community support the next time.  :)

I just set `"core_file_descriptor_ulimit" : 50000` in my Passengerfile.json.

It seems like the `application did not send a complete response` is gone.

However, I'm still experiencing the same `Cannot accept client: Too many open files (errno=24)` error followed `RuntimeException`.




```
2016/11/24 18:33:53 [error] 28243#0: *21327 connect() to unix:/tmp/passenger.ZVPhvnE/agents.s/core failed (11: Resource temporarily unavailable) while connecting to upstream, client: 127.0.0.1, server: _, request: "GET /salon/wunderhaar HTTP/1.1", upstream: "passenger:unix:/tmp/passenger.ZVPhvnE/agents.s/core:", host: "XXXX"
[ 2016-11-24 18:33:53.4471 28215/7f6a397fb700 Ser/AcceptLoadBalancer.h:150 ]: Resuming accepting new clients
[ 2016-11-24 18:33:58.3314 28215/7f6a397fb700 Ser/AcceptLoadBalancer.h:144 ]: Cannot accept client: Too many open files (errno=24). Stop accepting clients for 3 seconds.
[ 2016-11-24 18:34:01.3340 28215/7f6a397fb700 Ser/AcceptLoadBalancer.h:150 ]: Resuming accepting new clients
[ 2016-11-24 18:34:02.1346 28215/7f6a4919c700 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 28592, application XXXX (production)
[ 2016-11-24 18:34:02.1359 28215/7f6a3bfff700 age/Cor/Con/CheckoutSession.cpp:314 ]: [Client 2-2862] Cannot checkout session due to Passenger::RuntimeException: Cannot get user database entry for user UID 10000; it looks like your system's user database is broken, please fix it.
     in 'Passenger::SpawningKit::UserSwitchingInfo Passenger::SpawningKit::prepareUserSwitching(const Options&)' (UserSwitchingRules.h:66)
     in 'Passenger::SpawningKit::Spawner::SpawnPreparationInfo Passenger::SpawningKit::Spawner::prepareSpawn(const Options&)' (Spawner.h:717)
     in 'virtual Passenger::SpawningKit::Result Passenger::SpawningKit::DirectSpawner::spawn(const Options&)' (DirectSpawner.h:157)
     in 'void Passenger::ApplicationPool2::Group::spawnThreadRealMain(const SpawnerPtr&, const Passenger::ApplicationPool2::Options&, unsigned int)' (SpawningAndRestarting.cpp:95)
```

Please let me know if I should already ask follow like this one i n the community forum. I'll close this this issue then.

**Comment by OnixGH** [comment] 2016-11-24 18:02
I see: `(11: Resource temporarily unavailable)`. If you search for that on the same page you get to the [socket_backlog option](https://www.phusionpassenger.com/library/config/standalone/reference/#--socket-backlog-socket_backlog), have a look at that.

Tuning a system for massive load is a bit of an art, you need to take care of one bottleneck to find the next, which also depends on your system and load type, concurrency, etc. Since this is not a Passenger issue I'll close it, but it would be interesting to hear if the suggestion helped.

**Closed by OnixGH** 2016-11-24 18:02 UTC
Labels: SupportCentral
