### ISSUE TITLE
Passenger 5.2:  [BUG] Segmentation fault at 0x0000000000001246

### ISSUE THREAD

**Issue by Sega100500** [phusion/passenger#2022] opened 2018-01-30 09:32 UTC
Linux Debian 8 Jessise
Apache 2.4.10
Ruby 2.5.0 and Ruby 2.3.6 - different sites on different Ruby versions
different versions of Ruby on Rails

in passenger.log file:

```
App 11394 stderr: /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.2.0/src/ruby_supportlib/phusion_passenger/preloader_sh
ared_helpers.rb:79: [BUG] Segmentation fault at 0x0000000000001246
App 11394 stderr: ruby 2.3.6p384 (2017-12-14 revision 61254) [x86_64-linux]
App 11394 stderr:
App 11394 stderr: -- Control frame information -----------------------------------------------
App 11394 stderr: c:0007 p:---- s:0034 e:000033 CFUNC  :detach_process
App 11394 stderr: c:0006 p:0270 s:0030 e:000029 METHOD /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.2.0/src/ruby_supp
ortlib/phusion_passenger/preloader_share
App 11394 stderr: c:0005 p:0288 s:0022 e:000021 METHOD /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.2.0/src/ruby_supp
ortlib/phusion_passenger/preloader_share
App 11394 stderr: c:0004 p:0143 s:0009 e:000008 CLASS  /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.2.0/src/helper-sc
ripts/rack-preloader.rb:157
App 11394 stderr: c:0003 p:0011 s:0006 e:000005 CLASS  /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.2.0/src/helper-sc
ripts/rack-preloader.rb:30
App 11394 stderr: c:0002 p:0038 s:0004 E:001630 EVAL   /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.2.0/src/helper-sc
ripts/rack-preloader.rb:29 [FINISH]
App 11394 stderr: c:0001 p:0000 s:0002 E:000690 (none) [FINISH]
App 11394 stderr:
App 11394 stderr: -- Ruby level backtrace information ----------------------------------------
```

and more

```
App 11394 stderr:
App 11394 stderr: -- Machine register context ------------------------------------------------
App 11394 stderr:  RIP: 0x0000000000001306 RBP: 0x00007f2440001bba RSP: 0x00007f243fcf63c8
App 11394 stderr:
App 11394 stderr:  RAX: 0x0000000000000000 RBX: 0x00007f2440001960 RCX: 0x00007f243fcf8158
App 11394 stderr:  RDX: 0x00007f2449488590 RDI: 0x0000557b3d0f7b58 RSI: 0x0000557b3d0f5060
App 11394 stderr:   R8: 0x0000000000000003  R9: 0x0000557b3d0f75e0 R10: 0x0000557b3d0f3bd0
App 11394 stderr:  R11: 0x00007f243fcf8198 R12: 0x00007f2440001960 R13: 0x0000557b3d0f5060
App 11394 stderr:  R14: 0x0000557b3d0f7b58 R15: 0x0000000000000001 EFL: 0x0000000000010202
App 11394 stderr:
App 11394 stderr: -- C level backtrace information -------------------------------------------
[ W 2018-01-30 14:14:22.4245 11364/Ti age/Cor/Spa/SmartSpawner.h:750 ]: An error occurred while spawning a process: read() failed: Connection
reset by peer (errno=104)
[ W 2018-01-30 14:14:22.4245 11364/Ti age/Cor/Spa/SmartSpawner.h:751 ]: The application preloader seems to have crashed, restarting it and try
ing again...
[ W 2018-01-30 14:14:22.4257 11364/T8 age/Cor/Con/InternalUtils.cpp:96 ]: [Client 1-1] Sending 502 response: application did not send a comple
te response
```

**Comment by CamJN** [comment] 2018-01-31 21:23
duplicate of https://github.com/phusion/passenger/issues/2013

**Closed by CamJN** 2018-01-31 21:23 UTC
Labels: SupportCentral
