### ISSUE TITLE
Passenger crashes Apache macOS 10.13.x

### ISSUE THREAD

**Issue by jcrate** [phusion/passenger#2064] opened 2018-04-14 13:22 UTC
## Issue report

**Question 1: What is the problem?**

In an Apache setup with multiple vhosts, some of which are plain PHP sites, Passenger is crashing Apache when accessing the PHP sites. Using `PassengerEnabled off` at the directory, domain or server config level has no effect. Not loading Passenger at all allows the PHP sites to work.

The rails sites work fine, although some require `PassengerHighPerformance on`. Using `PassengerEnabled off` also prevents the rails apps from loading.

```
objc[84536]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[84536]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
[Sat Apr 14 08:46:37.815192 2018] [core:notice] [pid 84396] AH00052: child pid 84536 exit signal Abort trap (6)
```

**Question 2: Passenger version and integration mode**:
- For example: open source 5.0.26 standalone; enterprise 5.0.21/nginx

Passenger 5.2.3, installed via homebrew
* default homebrew-provided module
* module compiled with rvm ruby 2.4.3
* module compiled with rvm ruby 2.5.1

**Question 3: OS or Linux distro, platform (including version)**:
macOS 10.13.4

**Question 4: Passenger installation method**:

Your answer:
[ ] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[ ] Phusion APT repo
[ ] Phusion YUM repo
[X] OS X Homebrew
[ ] source tarball
[ ] Other, please specify:

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
Rails 4.2.x, 5.2.x, Ruby 2.3.x, 2.4.x. Rails sites work fine.
Passenger crashes when PHP 7.1.14 (default system PHP) is used.

Your answer:

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
No

**Question 7: Anything else about your setup that we should know?**

No
---

We strive for quality and appreciate you taking the time to submit a report! Please note that if you want guaranteed response times and priority issue support we encourage you to join our [enterprise customer](https://www.phusionpassenger.com/enterprise) base. They also provide us with the means to continue our high level of open source support!

**Comment by CamJN** [comment] 2018-04-18 16:16
Duplicate of https://github.com/phusion/passenger/issues/1986

**Closed by CamJN** 2018-04-18 16:16 UTC
Labels: SupportCentral

**Comment by jcrate** [comment] 2018-04-18 17:58
Apache/Passenger is crashing for the reasons outlined in #1986. This is not about that, using PassengerHighPerformance allows Passenger to serve the rails apps just fine.

This problem is about Passenger crashing Apache while serving a PHP site (not using Passenger) that Passenger is **not** servicing. Disabling Passenger using PassengerEnabled has no effect, even at the server config level. 

To summarize: 

- Passenger **can** be used on macOS 10.13 with case-insenstive file systems to serve Rails apps if you can use PassengerHighPerformance. 
- Passenger **cannot** be used with Apache on macOS 10.13 if you need to serve a PHP site, even though the documentation for the PassengerEnabled directive indicates that is what it could be used for.
