### ISSUE TITLE
Permission problem on OpenBSD 5.8 / nginx-1.9.3 / passenger-5.0.14

### ISSUE THREAD

**Issue by peterljung** [phusion/passenger#1667] opened 2015-11-13 20:46 UTC
I have some permission problem after an upgrade to OpenBSD 5.8. Any hint what problem I might have? I'm confused by the error message as the file has been created ...

```
2015/11/13 21:36:15 [alert] 20186#0: could not create /tmp/passenger.g9krmg4/web_server_control_process.pid (13: Permission denied)
2015/11/13 21:36:15 [alert] 24799#0: could not create /tmp/passenger.g9krmg4/web_server_control_process.pid (13: Permission denied)
2015/11/13 21:36:15 [alert] 8203#0: could not create /tmp/passenger.g9krmg4/web_server_control_process.pid (13: Permission denied)
2015/11/13 21:36:15 [alert] 11025#0: could not create /tmp/passenger.g9krmg4/web_server_control_process.pid (13: Permission denied)
2015/11/13 21:36:19 [crit] 20186#0: *1 connect() to unix:/passenger_core failed (13: Permission denied) while connecting to upstream, client: 192.168.0.1, server: blog.dittlag.se, request: "GET / HTTP/1.1", upstream: "passenger:unix:/passenger_core:", host: "blog.dittlag.se"
2015/11/13 21:36:19 [crit] 20186#0: *1 connect() to unix:/tmp/passenger.g9krmg4/agents.s/core failed (13: Permission denied) while connecting to upstream, client: 192.168.0.1, server: blog.dittlag.se, request: "GET /favicon.ico HTTP/1.1", upstream: "passenger:unix:/tmp/passenger.g9krmg4/agents.s/core:", host: "blog.dittlag.se", referrer: "http://blog.dittlag.se/"

# ls -l /tmp/passenger.g9krmg4/
total 28
drwxr-xr-x  2 www  www  512 Nov 13 21:36 agents.s
drwx--x--x  2 www  www  512 Nov 13 21:36 apps.s
-rw-r--r--  1 www  www    4 Nov 13 21:36 core.pid
-rw-r--r--  1 www  www    0 Nov 13 21:36 creation_finalized
-rw-------  1 www  www   24 Nov 13 21:36 full_admin_password.txt
-rw-r--r--  1 www  www    0 Nov 13 21:36 lock
-rw-r--r--  1 www  www  359 Nov 13 21:36 properties.json
-rw-------  1 www  www   24 Nov 13 21:36 read_only_admin_password.txt
-rw-r--r--  1 www  www    5 Nov 13 21:36 watchdog.pid
-rw-r--r--  1 www  www    0 Nov 13 21:36 web_server_control_process.pid

# uname -a
OpenBSD core.lounge.se 5.8 GENERIC.MP#1236 amd64

# pkg_info
...
ruby22-passenger-5.0.14 ruby web application server/nginx module
...
nginx-1.9.3p3-passenger robust and small HTTP server and mail proxy server
...

# ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-openbsd]

# whereis ruby
/usr/local/bin/ruby

# cat /etc/nginx/nginx.conf

user  www;

worker_processes        4;              # To use 4 cores
worker_rlimit_nofile    1024;           # Make sure sysctl.conf and login.conf reflect this

events {
    worker_connections  1024;
}

http {
    include             mime.types;
    default_type        application/octet-stream;

    keepalive_timeout   65;

    # The passenger root. (passenger-config --root)
    passenger_user_switching off;
    passenger_root      /usr/local/lib/phusion-passenger22;
    passenger_ruby      /usr/local/bin/ruby;

    # Optional passenger configuration
    passenger_max_pool_size     20;
    passenger_log_level         0;

    passenger_default_user      www;            # Only used when user switching fails
    passenger_default_group     www;            # See modrails docs

    rails_spawn_method          smart;
    passenger_pool_idle_time    0;              # (seconds) 0 = don't shut down if not neccesary

    include             /etc/nginx/sites-enabled/*;

    server {
        listen                  80;
        server_name             blog.dittlag.se;

        root                    /var/www/pages/rails/eman-blog/public;
        passenger_enabled       on;
        rails_env               production;
    }
    passenger_pre_start http://blog.dittlag.se/;
}

```

**Comment by OnixGH** [comment] 2015-11-14 17:21
Does this happen with 5.0.21 as well?

**Comment by peterljung** [comment] 2015-11-15 20:23
I have not been able to try out 5.0.21 yet. I use the default prebuilt package for OpenBSD.
It seems that OpenBSD requires a lot of patches for passenger so I will need to patch the package source first and rebuild the package in that case.

<http://cvsweb.openbsd.org/cgi-bin/cvsweb/ports/www/ruby-passenger/patches/>

I can also check with OpenBSD ports maintainer for some tips.

Is there a problem to create the file `web_server_control_process.pid`? File folder permission problem? 

    /tmp/passenger.g9krmg4/web_server_control_process.pid (13: Permission denied)

The file has been created but it has size 0.

    -rw-r--r--  1 www  www    0 Nov 13 21:36 web_server_control_process.pid

Is there something else I can do to narrow down the problem?

**Comment by peterljung** [comment] 2015-11-15 20:35
Running passenger stand alone works fine by the way ...

    cd /var/www/pages/rails/eman-blog/                                                                                                                                           
    # passenger start -e production --user www

So, passenger seems fine by itself.

**Comment by OnixGH** [comment] 2015-11-16 09:38
Aha, the patchlist shows that the package was upgraded from passenger 4 to passenger 5, a big step in general, so maybe the package maintainer can do a quick check. I'm not very familiar with OpenBSD but something that's easy to try is to set [passenger_instance_registry_dir](https://www.phusionpassenger.com/library/config/nginx/reference/#passenger_instance_registry_dir) to another location than the default /tmp.

**Comment by OnixGH** [comment] 2015-11-17 11:20
Any word from the package maintainer?

Btw. /tmp and /var/www/ aren't by any chance mounted on network storage (e.g. NFS)? Because that wouldn't work.

**Comment by peterljung** [comment] 2015-11-17 16:21
Not yet. Waiting for response...

**Comment by peterljung** [comment] 2015-11-17 16:23
And no network storage...

**Comment by peterljung** [comment] 2015-11-22 19:40
I believe the port may not be actively maintained and I will try another setup on OpenBSD 5.8.
Its no real hurry for me as I have a working setup on OpenBSD 5.6.

**Comment by OnixGH** [comment] 2015-11-26 15:44
Ok, we'll hang back a bit for word from the maintainers, or a new version, or some other information that would help debug the issue :)

**Comment by OnixGH** [comment] 2016-06-23 12:00
Closing this one for now due to lack of information, feel free to reopen if the issue is still relevant and there is new information.

**Closed** 2016-06-23 12:00 UTC
Labels: CannotReproduce

**Comment by brycied00d** [comment] 2016-08-03 02:23
@peterljung I too have run into this issue and the cause was OpenBSD's default of running nginx chroot'd. If you `rcctl set nginx flags -u` and `rcctl restart nginx` I think you'll find that everything starts up as expected.

My apologies for resurrecting this "dead" issue. I wanted to bring this issue closure, as well as possibly solving the issue for you, avoiding a https://xkcd.com/979/ situation for someone in the future.

**Comment by peterljung** [comment] 2016-08-03 09:01
That seems like a reasonable reason for my problems. Thanks for clarifying this!

I have since then moved to a different setup using [puma.io](https://puma.io).
