### ISSUE TITLE
rack requires Ruby version >= 2.2.2

### ISSUE THREAD

**Issue by mwaldner-redfall** [phusion/passenger#1711] opened 2015-12-23 22:54 UTC
Hi, when Installing the latest version of passenger:

`gem install --version 5.0.23 --no-user-install --no-rdoc --no-ri passenger`

I get the following errors:

```ERROR:  Error installing passenger:
rack requires Ruby version >= 2.2.2.```

My Ruby gems version
```gem -v```
2.0.14.1

Any ideas? Or is upgrading to 2.2.2 the only option?

Thanks

**Comment by OnixGH** [comment] 2015-12-24 07:31
Duplicate of #1710

**Closed by OnixGH** 2015-12-24 07:31 UTC
Labels: SupportCentral
