### ISSUE TITLE
Unable to start Nginx

### ISSUE THREAD

**Issue by Rubioli** [phusion/passenger#1823] opened 2016-06-09 16:08 UTC
I am using Digitalocean as my server.

I installed Ubuntu 16.04 with Nginx. It looks like Passenger isn't bundled into my Nginx configuration and this prevents my server/Nginx to start.

Does Phusion Passenger have packages for ubuntu 16.04? and how can solve my issue?

Thanks

**Comment by OnixGH** [comment] 2016-06-09 19:26
Duplicate of #1807

**Closed by OnixGH** 2016-06-09 19:26 UTC
Labels: SupportCentral
