### ISSUE TITLE
upstream prematurely closed connection while reading response header from upstream

### ISSUE THREAD

**Issue by terrybleger** [phusion/passenger#1320] opened 2014-12-12 23:12 UTC
I don't understand why can't node handles error 502/504 when using passenger? I've put try catch inside my code. Any error can be handled except 502 & 504.

1. I don't wanna increase the timeout. Because it's useless, the error can't be handled anyway.
2. I don't wanna nginx to handle it. Because it needs to be processed first before sending it back to the client.
3. I don't even think any buffer_*** matter. All I want is just if there is an error I want it to be able to handle it my self.
4. I've tried using ```passenger_ignore_client_abort on;```. It didn't even solve my problem anyway.

Why can't passenger lets node to handle it?

This is just a simple piece of code:
```
try {
  let response = yield request(opt);
} catch (err) { console.log(err); } 
```

OSX doesn't have the problem. I'm using Ubuntu 14.04, Phusion Passenger version 4.0.53.

```
[error] 27522#0: *26 upstream prematurely closed connection while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: , request: "POST /api/transaction HTTP/1.1", upstream: "passenger:/tmp/passenger.1.0.27501/generation-0/request:", host: "xxx.xxx.xxx.xxx"

[error] 4010#0: *110 upstream prematurely closed connection while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: , request: "POST /api/transaction HTTP/1.0", upstream: "passenger:/tmp/passenger.1.0.3990/generation-0/request:", host: "xxx.xxx.xxx.xxx"
```

**Comment by webmakin** [comment] 2015-01-08 09:31
I am having the same issue, please can someone look into this.
Also i found something on nginx side,  https://chrislea.com/2013/02/23/proxying-websockets-with-nginx/#comment-68

**Comment by FooBarWidget** [comment] 2015-01-08 11:00
Let me schedule this for RC1 for now.

**Comment by 12preschph** [comment] 2015-02-14 17:21
+1

**Comment by FooBarWidget** [comment] 2015-02-16 13:47
I'm ready to work on this issue, but I'm having trouble understanding it. What exactly is the issue here? Are you saying that you expect Passenger to catch exceptions and to return default 500 responses in those cases? What are you expecting from Passenger?

**Comment by FooBarWidget** [comment] 2015-02-27 13:39
@terrybleger @webmakin Do you have any further feedback? I'd like to solve this issue as soon as possible, but I can't do it without your help.

**Comment by webmakin** [comment] 2015-03-12 12:59
@FooBarWidget Since i had to move to a PaaS provider for lack of time i have discarded the setup i had. However I will be replicating this setup very soon, will update if I find the same issue again.

**Comment by terrybleger** [comment] 2015-03-13 04:38
@FooBarWidget 

Sorry for having late reply.

Currently I haven't had the time to test it against the latest version of passenger.

As I mention before the problem lies when using passenger, node.js is unable to catch exception for error 502 & 504 only, the other 5xx I don't know. I've tested it on OS X and had no problem. But on Linux (Ubuntu 14.04) the problem arise. So, since node.js is unable to catch the error, it will just creates nightmare. When not using passenger (standard nginx reverse proxy configuration), node.js is able to catch the error. That's why I'm questioning why?

**Comment by FooBarWidget** [comment] 2015-03-13 08:55
Passenger doesn't interfere with exceptions. All exception handling should work fine. You posted a small code snippet, but it is not complete. My attempts to make a reproducible test case have also failed. Could you post a full program for me to analyze? Could you also tell me which Node.js/io.js version you are using?

**Comment by FooBarWidget** [comment] 2015-03-28 12:18
@12preschph Are you able to tell us how to reproduce this problem? We haven't had any luck so far, and without further feedback there is little we can do about this issue.

**Comment by FooBarWidget** [comment] 2015-04-07 15:23
I'm closing this issue for now until someone can help us shed more light on this problem.

**Closed** 2015-04-07 15:23 UTC
Labels: NeedsFeedback

**Comment by vatnoise** [comment] 2016-08-05 14:02
Is it related to using nginx or sockets by any chance?

I just found this thread by googling a similar error but I'm trying to use a websocket and ZeroMQ PHP extension to connect to sockets via tcp and in my case it works perfectly on my local machine (LAMP) but on the production server we also have nginx thrown into the mix and that seems to give errors like:

    (104)Connection reset by peer: mod_fcgid: error reading data from FastCGI server, referer: http://website/_test/send.php

    upstream prematurely closed connection while reading response header from upstream

    2016/08/05 14:27:22 [error] 19214#0: *155952 upstream prematurely closed connection while reading response header from upstream, client: 217.**.**.***, server: my.domain.name, request: "POST /_socket/send.php HTTP/1.1", upstream: "http://78.***.***.**:7080/_socket/send.php", host: "my.domain.name", referrer: "http://my.domain.name/_test/chat.php"
