### ISSUE TITLE
PassengerPoolIdleTime 0 causes crash

### ISSUE THREAD

**Issue by esb** [phusion/passenger#2034] opened 2018-02-17 22:01 UTC
Just upgraded to 5.2.0 and my current configuration causes Passenger to crash.

```
<IfModule mod_passenger.c>
  PassengerRoot /usr/local/rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/passenger-5.2.0
  PassengerDefaultRuby /usr/local/rbenv/versions/2.4.2/bin/ruby
  PassengerUserSwitching off
  PassengerDefaultUser apache
  PassengerDefaultGroup apache
  PassengerLogLevel 0
  PassengerSpawnMethod smart
  PassengerHighPerformance on
  PassengerStartTimeout 240
  PassengerMaxPoolSize 3
  PassengerMinInstances 1
  PassengerPoolIdleTime 0
</IfModule>
```

If I comment out the 'PassengerPoolIdleTime 0' statement, it all works.

**Comment by OnixGH** [comment] 2018-02-17 22:03
Duplicate of #2020

**Closed by OnixGH** 2018-02-17 22:03 UTC
Labels: SupportCentral
