### ISSUE TITLE
Bad signing key for Ubuntu Trusty repo

### ISSUE THREAD

**Issue by WillPlatnick** [phusion/passenger#1815] opened 2016-05-26 12:56 UTC
When trying to run apt-get update/upgrade, we get the following error:

apt-get update:
W: GPG error: https://www.phusionpassenger.com trusty Release: The following signatures were invalid: BADSIG 561F9B9CAC40B2F7 Phusion Automated Software Signing (Used by automated tools to sign software packages) <auto-software-signing@phusion.nl>

apt-get upgrade
WARNING: The following packages cannot be authenticated!
  nginx-common nginx-extras passenger-enterprise-dev passenger-enterprise
  passenger-enterprise-doc

**Comment by FooBarWidget** [comment] 2016-06-01 02:49
This is a duplicate of #1807.

**Closed by FooBarWidget** 2016-06-01 02:49 UTC
Labels: SupportCentral
