### ISSUE TITLE
Passenger 5.0.2 on Ubuntu no longer service Node.js apps

### ISSUE THREAD

**Issue by nikolay** [phusion/passenger#1417] opened 2015-03-09 19:33 UTC
A server that was perfectly working on `v4` got upgraded to `v5`. After I removed the inclusion of `passenger.conf`, which is no longer supported, the app only serves the public folder and none of the Node.js code is executed resulting only in 404s.

**Comment by nikolay** [comment] 2015-03-09 19:47
Even after I added `passenger_log_level 5;` to `nginx.conf`, I don't see anything Passenger-specific in the `error.log` of Nginx.

**Comment by FooBarWidget** [comment] 2015-03-09 20:12
Could you post your Nginx configuration file for review?

**Comment by nikolay** [comment] 2015-03-09 20:19
@FooBarWidget I'm using the configuration from your documentation without any changes. When I run Passenger standalone with the same app, it works fine, but Passenger doesn't seem to work at all within Nginx if I don't even get debug-level output from it. Of course, `passenger_enabled on;` is there and Nginx is not complaining. I did upgrade to in-place, then, I did `apt-get purge passenger && apt-get autoremove`, installed anew, recompiled Nginx, and it is still not working.

**Comment by FooBarWidget** [comment] 2015-03-09 20:31
Node.js support should still work fine. Our blog is a Node.js app (Ghost) running on Passenger 5 and it works smoothly. There is probably something else going on here.

First, could you check whether -- after Nginx is started -- Passenger is running? You can do this by running passenger-memory-stats. Do you see any Passenger processes?

Next, could you check whether you're looking in the right Nginx error log file? You can do this by running:

    passenger-config admin-command GET /config.json

The "log_file" field tells you where errors are logged to. If it's a different file from the one you looked at earlier, can you look there and check whether there is anything relevant?

I apologize if I respond slowly. I caught a cold over the weekend. But I'll try to help you as best as I can.

**Comment by nikolay** [comment] 2015-03-09 20:35
@FooBarWidget That's fine and I understand, but the issue for me is that it seems that the old releases are not available in the Ubuntu repository so that our servers in EC2 that are getting launched via autoscaling are now broken. Give me a few and I will provide the outputs you requested.

**Comment by FooBarWidget** [comment] 2015-03-09 20:37
Passenger 4 is available in a separate APT repository if you need that: https://blog.phusion.nl/2015/03/08/passenger-4-apt-repository-now-available/

**Comment by FooBarWidget** [comment] 2015-03-16 14:29
Hi @nikolay, could you check your Nginx error log file as I described earlier?

**Comment by FooBarWidget** [comment] 2015-03-18 11:39
@OnixGH Are you able to reproduce this issue?

There is an email on the mailing list that look like it's related to this issue. As you able to reproduce that too? https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/phusion-passenger/q5S1hRP03Ns/KFtsPPt5HMEJ

**Comment by OnixGH** [comment] 2015-03-18 14:40
@FooBarWidget the issue in the mailing list is for passenger 4, and it looks to me like that one is more of an Apache configuration problem, so probably not related.

**Comment by OnixGH** [comment] 2015-03-19 11:52
@nikolay I don't know what you mean by "After I removed the inclusion of passenger.conf, which is no longer supported", nginx 1.6.2 still supports include files. We're also not sure what your setup is exactly (there are many ways to install and we have more than one configuration). For example apt installs configs to /etc/nginx but if you compile the default is /opt/nginx.

You can try running nginx -t to see if that looks at the config file you are expecting. Other than that I'm afraid we can't help without further information, as we don't get the problem here.

**Comment by FooBarWidget** [comment] 2015-03-28 12:16
Because we can't do anything about this issue without feedback, I'm closing this issue for now. If anybody still experience this issue, please let us know and we'll reopen the issue and look into the problem.

**Closed by FooBarWidget** 2015-03-28 12:16 UTC
Labels: NeedsFeedback, Priority/High
