### ISSUE TITLE
Passenger does not compile on OSX Yosemite

### ISSUE THREAD

**Issue by d-snp** [phusion/passenger#1347] opened 2015-01-12 14:33 UTC
As reported by Rachael Carey:

After I run brew install passenger, I try to install the passenger-install-apache2-module which fails with the following:
...
rm -f buildout/libev/libev.la
cd buildout/libev/ && make libev.la
make: *** No rule to make target `/private/tmp/passenger-tTTlwc/passenger-4.0.57/ext/libev/ev.c', needed by `ev.lo'.  Stop.
rake aborted!
Command failed with status (2): [cd buildout/libev/ && make libev.la...]
/usr/local/Cellar/passenger/4.0.57/libexec/build/common_library.rb:143:in `block in <top (required)>'
Tasks: TOP => apache2 => buildout/agents/PassengerHelperAgent => buildout/libev/.libs/libev.a

I'm running yosemite and tried running adapts the system ruby, then installed rbenv and upgraded it to 2.2.0 but still get the same error both times.

**Comment by FooBarWidget** [comment] 2015-01-14 11:14
Duplicate of #1288.

**Closed by FooBarWidget** 2015-01-14 11:14 UTC
